# 2024.08.23杭州场 {#hangzhou-20240823}

## Part1 
🎵【借过一下】杭州的朋友们，你们好吗？

🎵【Monsters】【化身孤岛的鲸】这首歌你们愿意跟我一起唱吗？你们～ 看台的朋友大声点哦～ 到你们哦～ 看台的～ （没有墙头）我不相信～ 
杭州的朋友们你们好，大莲花我们来啦～ 我想想，我学了一句的，杭州的朋友们大家好，你们吃过了吗？（杭州话）谢谢大家，大家好我是歌手周深，你们好吗？我们的演唱会主题叫做9.29Hz，曾经我也觉得自己特别像是9.29Hz这样的频率，没有办法被听到，但是谢谢每一个你，你们听到了我，看到了我，谢谢你们，所以如果你也觉得和我之前想法很像，自己也是没有办法被听到的话，那么我想告诉你，你不会孤单的，因为我会听到你们～ 
好，那接下来这首歌，我觉得就自己在，很多时候就自己在事业道路上，或者是在寻找更好的自己的那个路上，有时会觉得很孤单，会甚至有时觉得路上有点黑，但是因为你们的出现，照亮了我的路，因为你们是我的光亮，谢谢你们～ 然后今天这首光亮也有我们新的，这算是老朋友了吧，大家掌声欢迎钱雷老师，我给你个机会给大家打招呼。（钱雷：杭州的朋友们大家好，我是现代人钱雷）啥，雷哥其实一直住在杭州，那你会说几句杭州话吗？（钱雷：不会）音乐人是比较直接和诚实的，好，那我们一起把这首光亮送给大家，你们都说我治愈了你们，其实你们才是治愈我的那个人，谢谢你们给我的光亮，谢谢～ 

🎵【光亮】你们好吗？ 谢谢每个看到我听到我的人，你们照亮了我的全部，谢谢大家，也谢谢雷哥，掌声给雷哥～ 
宝你个头！

🎵【若梦】等下要跟我一起唱哦～ 到你们哦～ 看台的朋友，大声点～ 谢谢你们，太好听啦～ 到你们哦～ 全场一起～ 大声点～ 你们唱的太好听啦～  

🎵【浮光】这首歌会跟我一起唱吗？（会）那等下要唱大声点哦～ 到你们～ 谢谢在这恍惚三万天当中，你们看见了我，听到了我，谢谢大家，我是歌手周深～ 

## Part2 

🎵【蜃楼】【警报】掌声给我们的舞蹈老师们～ 
大家好，我是歌手周深，你们好吗？杭州的朋友们你们好吗？看台的朋友你们听到了吗？这边的朋友你们好吗？我听说，就是听说哦，我也从来没有这样体验过，就是在演唱会，手指到哪里哪里就会有欢呼声，是真的吗？这边呢，这边呢，那看台的那边会有吗，这边呢，那如果是这样呢？哇塞，你们太棒了，给自己鼓掌～ 谢谢大家，谢谢你们给我安全感，让我愿意去把新的周深的一面去介绍给大家，前面第一部分比较古风飘渺的是比较大家熟悉的周深 ，刚才演唱的是新专辑反深代词，反深代词的深是周深的那个深，我记住了～ 反深代词的新歌第一个蜃楼写的执念，警报写的是要好好爱自己，那今天要唱的这首歌叫做缝合，我觉得自己很幸运可以成为一个歌手，因为这特别像这首歌里面写的200年后的缝合机器人一样，他可以不停的去缝我们人类受到的创伤，无论是小的时候还是长大之后，虽然他的这个缝合或者是我的歌声，不会把所有的伤口缝补得像伤害从来没有来过一样，但是其实很多时候我会发现，你们才是那个用爱去缝合我的人，所以我觉得特别特别幸福，哪怕我们所有的缝合这个动作，他不会让那些伤害消失，不会让那些伤害像没有来过一样，但正是因为我们互相用爱去缝合彼此，这就是缝合的意义，谢谢你们。真的非常荣幸能够出现在大家生命当中，谢谢你们听见了我，我们继续用爱缝合彼此好吗？

🎵【缝合】好好的爱自己，你们没有必要要做到完美，没有必要做到100分，我爱你们～ 

🎵【天堂岛之歌】谢谢老师们～ 糟糕糟糕，爱你们这件事，我逃不出去啦，哪怕你们墙头这么多，（没有）没有吗？那边的也没有吗？那边的也没有吗？连看台的也没有吗？那我就要考验一下，有一个童话故事，那个主角的名字叫做？人多就是有个好处，哪怕你们背错了我也听不出来，看台的朋友再来一遍，达啦崩吧～ 哦，那全场他打败的那条巨龙叫做？哇塞，有点厉害哦，杭州的朋友们非常棒哦～ 杭州的朋友们，那这首歌我们一起来再想想，到底是谁为了拯救谁，然后打败了谁，他们回到了哪里，好吗？也希望我们都能拥有童话般的浪漫～ 

🎵【达啦崩吧】看台的朋友～ 杭州的朋友们，到你们了哦～ 到底是谁拯救谁，打败谁，又回到哪里呢？准备好了吗？于是～ 砍向～ 然后～ 咬了～ 最后～ 恭喜我们成功啦～ 
谢谢大家，非常非常开心，能够用很多形式让大家看见，比如像是奔跑吧里面活泼的我，然后也像是电影、或电视剧OST里的我，大家都有从这些途径看到我嘛？那要说到写歌非常好听的人，大家一定会想到？你们情商着急啊，刚才才请完人家钱雷老师，重新来一下，呀，我们都当刚没发生过，321，哎呀，如果要说写歌写得非常好听，我们一定要提到？掌声欢迎他，他又来啦～ 这么内向，大家提到钱雷老师，第一个会提到什么歌？应该是，爱你孤身走暗巷～ 雷哥，这次要好好跟大家打招呼，正儿八经的打招呼～ （钱雷：大家好，我是反深代词的，呃，制作人）那，我想问一个，你写歌的时候有没有想过，自己是不是人这个问题～ （钱雷：我是手机）哈哈哈，因为雷哥写的歌都太难了，所以当时为什么要把歌写那么难？（钱雷：因为你能表达的非常好，你要是唱不上去，我也不带那么写的）那我只能说，把歌写的这么难，我就是很有压力连开什么三四五场，都是雷哥背的锅，那大家要是找你的话，你会怎么说？（钱雷：找我？？？？）好了，音乐人最擅长的就是用音乐跟大家对话，希望大家喜欢这首歌，人是_，是人吗，写那么难？

🎵【人是_】大声点～ 我们一起～ 大声点～ 掌声给钱雷老师，谢谢你们，太棒啦～ 

## Part3 
Hello hello大家好，你们找得到我在哪吗？我在这里～ 杭州的朋友们你们好！接下来要演唱的歌都非常的浪漫和温馨，甚至浪漫到我们的舞台只转过来一半，就想看下你们岂不期待我的出现啊？谢谢你们，如果说，就是相遇是～ 我觉得所有的话都在接下来两首歌中，希望你们能喜欢这两首歌好吗？我也老大不小了，学一个新的技能我也很开心，但是希望你们能够给我鼓励好吗？也想告诉你，想学一个事情，任何时候都不晚，记住了吗？

🎵【My Only + Rubia】你一定要记住你们是点亮我的每一束光好吗？也谢谢你们，愿意接住我的每一个碎片，哪怕那个碎片它不完美，甚至说是有一些缺点，但是谢谢你们接住了我，谢谢你们～ 
接下来这首歌，你们要跟我大合唱好吗？那它是什么歌呢？

🎵【小美满】会唱吗？那要跟我一起唱吗？看台的朋友大声点哦～ 全场～ 你们太棒啦，你们的版本真的太好听啦～ 再大声一点好吗？大声点哦～ 再大声～ 谢谢你们，在这个夏天跟我相遇，夏天很快要过去了，但是谢谢你们陪我闯过风，闯过雨，然后我们身上流的每一滴汗，或者说我们创造的每一个记忆，在每一个夏天到来的时候，我都会想起来，谢谢你们给我的这些小美满～ 小美满这首歌特别的美好，所以我觉得它特别适合许愿，我们一起在这里许愿好不好？就像我这样，许一个愿望，321，它就会挂在这颗许愿树上，现在我们全场的朋友，跟我一样，闭上眼睛，听话，无论你是做什么职业，什么年纪的，现在闭上眼睛，默默想好那个愿望，默默想好那个愿望，想想你想许什么愿望呢，但是这个愿望有一个要求，就是只能够关于你自己，现在闭上眼睛，想想这个愿望，有多久没有好好的问候一下自己，没有好好的问一下自己，最近过的好吗，想好了吗？321，你们的愿望一定会被听见的～ （唱：你们就是周深最好的陪伴～ ）也希望遇见我这件事情能成为你生活中的小美满好吗？

🎵【花开忘忧】我来到你们家里啦～ 希望大家像小美满里面一样，好好的爱自己好吗？这样爱你的人才不会为你担心，一定要做到哦～ 我们一起～ （我们苍老的时候，就回到小时候）我们的思念，我们的爱，离开的人一定听得到，对吗？我以前觉得自己喊的不够大声听不到，但是谢谢你们，我觉得他、他们一定都听得到对不对？谢谢～ 
嘤嘤嘤～ 谢谢你们～ （换衣服）到底是为什么我换衣服。。。你们，这里有没有谁是第一次来看演唱会的？这么多吗？哦那你们是第一次看演唱会就在这里跟我们一起相遇的吗？哦，谢谢你们，那有没有谁，就是听到，就是第一次听到歌声是听到周深呢？骗子，你出生前，这两位直接哈哈哈哈，难道你们在遇到我之前都没听到歌吗？难道你们就从来没在路边听到哪怕是啊啊啊啊～ 的歌吗？骗子，但是这个善意的谎言，我就选择相信一下，哇，原来有这么多人是因为我才喜欢听歌的，谢谢你们～ 但是，第一个算是启蒙我唱歌的歌手，她叫邓丽君女士，所以这里有没有人喜欢听她的歌呢？所以我觉得邓女士她每首歌当中都会有很多的时光胶囊，有很多他们的回忆，所以我也希望自己能够成为像一个像邓女士这样的歌手陪伴大家好吗？或者隔了再多再多年，大家还是会想起周深的歌，周深的歌声，但是无论后面怎样，现在我觉得周深非常幸福，因为遇到了你们，你们看见了我，听到了我，谢谢你们～ 等下会唱的话跟我一起唱哦～ 你们唱得好吗？（好）唱得这么好那你们上来唱？等下跟我一起唱好吗？

🎵【邓丽君歌单组曲】你们可棒啊～ 摇起你们手中的荧光棒～ 到你们唱哦～ 看台的朋友也听好哦（路边的野花，你不要采）全场～ 大声点～ 你们会忘记我吗？谢谢你们～ 大声点～ 全场一起好吗？不要忘了我好吗？

## Part4 
大家好，我都听到了哦，爱你个头啊～ 宝你个头啊～ 

🎵【听我说+望】大声点，看台的朋友大声点哦～ 大家要找我说哦～ 我们一起好吗～  看台的朋友大声点～ 谢谢你们，兜兜转转，绕啊绕，最后我们还是相遇啦，谢谢你往前迈的每一步～ 谢谢你们从来没有放开那根牵着我的线，看台的朋友们，你们好吗？大声点～ 因为你你你你……你你你的存在，我才心有所住～ 无论你在哪（唱：不必害怕孤独）无论你在哪，我都在这，好吗！谢谢你们，你们太棒啦～ 杭州的朋友们，你们太棒啦～ 
要说到杭州，第一个大家想到的是，西湖，以及西湖醋鱼，但是，这是我们外地人，以前我从小就觉得，我真的很想去看下断桥，真的好想去看下西湖，因为有个特别美丽的神话故事，它叫做？（白娘子）被拍成了电视剧，它里面的片头曲，叫做千年（千年等一回），我很开心，我们的相见，我只等了10年，但是我也相信，一定是，就怎么说，我们从当中走的路，绝对也不比他们千年等一回走的少，所以谢谢你们走过来与我相遇，谢谢～ 那等一下愿意跟我一起唱这首千年等一回吗？（愿意）等下如果我唱千年等一回，你们要唱（等一回啊啊～ ）对，这个地方很棒，后面还有个地方，嘿哈嘿，好吗？我们来试一下，嘿哈嘿，唱？看台的朋友我没有听到你们声音哦，嘿哈嘿，唱？（嘿哈嘿）突然声音大到震耳欲聋～ 谢谢你们，和我一起唱这首千年等一回吧，因为我们10年才在这里相见，也是非常非常非常难得，谢谢你们，愿意来跟我相遇～ 

🎵【千年等一回】你们是最棒的观众～ 来洛～ 嘿哈嘿～ 这边看台的～ 断肠也无怨～ Chi Chi na～ （PS：China太好听了）看台的朋友～ 来了哦～ 嘿哈嘿～ 大声点～ 一起～ 你们～ 唱～ 看台～ 大声点～ 你们太棒啦，一起～ 你们唱得太好听啦，怎么合唱这首歌的时候，比小美满的声音还大呢，我生气了，我走了，哄不好了杭州的朋友们，我走了～ 那我可以再试一下吗？（唱：没什么大愿望）（没有什么事要赶）谢谢你们，一下就被哄好了，好开心啊～ 但是无论怎么样，就像我玩游戏一样，经常可能打不赢，但是只要我能获得快乐，我总能够赢一把吧。就像我们人生当中尝试很多事情，可能会有挫折，但是不要害怕，它就像可能今天大家会流很多汗，来为我们这次见面，对，扇得很用力，但是，每次一到夏天的时候，我的脑海中的记忆，一定会有这段记忆，对于我来说，是非常美妙的奇迹时刻～ 

🎵【奇迹时刻】这是一根红蜡烛～ 【魔术时间】但是需要你们大声喊出啊～ 321喊～ 还需要你们给我一个掌声好吗～ 321～ 谢谢大家！～ 
那以前我听过一个快乐的密码叫做Hakuna Matata，有人听过这个嘛？但是在我的新专辑当中，反深代词当中，叫做（wala li longla）看台的朋友知道吗？我们来试一下哦，大家跟着我一起念，wala～ wala li～ wala li long～ wala li longla～ 这是一个只要喊出来，你就会永远快乐的密码，记得在心情不好的时候，喊一句，wala li longla～ 

🎵【wala li longla】看台的朋友～ 大家一定要天天开心好不好？那接下来，我们一起念响这个快乐密码好吗？跟我一起哦，54321，wala，wala li，wala li long，wala li longla，看台的，wala，wala li，wala li long，wala li longla，看台的～ 你们是最棒的观众～ 杭州太棒啦～ 掌声给我们的舞蹈老师们～ 谢谢你们～ 我一直特别想跟你们说的一句话，虽然我说了非常非常多次，但是希望你们永远都能够相信，你们能够让一个普普通通的男孩子满满的去接近他的梦想，你们的力量，比你们想象的大的多，看台的朋友你们听到了吗？你们一直说是我照亮了你们，但其实是你们的光一直照在我的身上，让我开始愿意去看清自己，愿意去追逐更好的自己，谢谢你们，也希望我们每一个璀璨冒险人都可以收获属于我们的璀璨，璀璨冒险人，出发吧～ 

🎵【璀璨冒险人】和我一起～ 你们都是自己的英雄，一定要记住好吗？你们～ 全场～ 谢谢大家，璀璨冒险人们，周深可以做到的，你也一定可以做到！谢谢你们～ 

【点歌环节】那接下来，到我们的点歌环节哦，我的这个歌单非常考验到底听我的歌听了多久，因为它是相对来说，比较宝藏歌单的一些歌曲，但是我相信这些歌会是某一个人他心中的宝藏歌曲，对吗？谢谢谢谢～ 那等下我们会全场倒数五个数字，我们的摄像老师拍到谁，就会有请他帮我们点出这首歌好吗？全场跟我一起，我们摄像老师这边，转起来～ 全场～ 54321，停～ 啊，在哪，你在哪里？hello，你好，（你好），那有个麦克风，你好漂亮，（谢谢）应该怎么称呼你？（呃，叫我wulala）wulala？你和wala li longla的关系是？（也是一样爱你）现在点起来的人的攻击力越来越强了，爱你个头，（深深宝贝）爱你个头啊，宝你个头，（啊～ 开心）你是哪里来的朋友？（我从上海来）上海来的？哦～ 谢谢你谢谢你，今天非常非常漂亮。（谢谢～ ）那有听话每天都照顾好自己吗？（有的呀）有在我们相遇之前好好照顾好自己吗？ （有的呀，努力上班，赚钱，来看你演唱会）努力上班，赚钱，然后要先把看我这件事情放在照顾好自己后面，好吗？（当然当然）必须必须好吗？（好的）大家也要这样好吗？（好）听我的歌多少年了？（我算算，四五年吧）四五年，那还挺长，第一次听到我的歌是？（应该是China Voice）哦，就是我刚出道那个舞台是吧？那你对我印象最深的歌曲是？除了大鱼？（沉默）印象不深刻，明白了～ （太深刻了，每一首都喜欢，选不出来）啊，这下你之前的犹豫，就已经失败啦～ （哎呀，你懂的，我爱你）wu～ （宝贝）wulala朋友点歌吧，这些歌有你喜欢的歌吗？怎么会问你旁边的人？你的爱都是假的，耶，我又赢啦！（可是我照顾好自己，我也很爱她）哦，好叻～ 啥意思每听懂？哈哈（我照顾好自己嘛，所以我也很爱她，所以我问她喜欢听什么）真棒，我说不过你，我错了，我唱还不行吗？这些歌当中有没有你想听的歌？（我想听随风）哇塞，大家都想听随风嘛？看台的朋友也想听吗？哦～ 谢谢wulala，谢谢你，我也很喜欢这首随风，然后希望大家也能喜欢这首歌，也希望大家的烦恼都可以随风被吹走好吗？谢谢，随风，希望你们喜欢～ 

🎵【随风】你们会唱这首歌吗？（会）那等下要帮我一起唱哦～ 跟我一起好吗？谢谢～ 谢谢你，无论是从任何一首歌中听到了我，谢谢你看到了我～ 这首歌等下要跟我一起唱好吗？

🎵【不想睡】这个是当时，在网上唱卡布的麦克风哦～ 看出来了吗？宝你个头啊～ 跟我一起哦～ 到你们～ 看台的朋友大声点哦～ 谢谢你，听到了我，看到了我，谢谢你，看到了卡布，看到了歌手周深～ 全场跟我一起～ 看台的朋友大声点～ 希望你们能天天都开心～ 谢谢你，大家，大家真的辛苦了，无论你是从哪个地方过来跟我见面，一定克服了很多很多困难，也放下了自己很多很多事情，谢谢你愿意把这个时间抽出来与我见面，谢谢你愿意抽出来跟我创造这个美好回忆，谢谢你们～ 希望你们今天听的开心，玩的愉快好吗？当然也要感谢所有让我们好好的开心的安全的见面的所有幕后的工作人员对不对？那我们感谢场地支持杭州……【感谢中】杭州承办方…协办方也是反深代词的发行…谢谢大家，大家记得听一下我的新专辑反深代词哈，感谢感谢～ 也感谢我们的演唱会制作单位，感谢总导演…感谢我们的音响总监…感谢我们的音乐总监…【继续感谢中】以及乐队老师们，还有我们的合唱老师们～ 还有我们的特别嘉宾就是雷哥，也感谢我们的舞蹈团队….感谢服装团队…感谢时装品牌…感谢我们音响工程…感谢调音团队…感谢…怎么会写一个保帅如雷啊～ 哈哈～ 感谢我们的周深工作室的小伙伴们～ （啊啊啊～ ）你们真的太好了，谢谢大家，我们还会继续努力继续进步，希望能照顾好大家，感谢微博～ （倒闭）感谢微博音乐～ （倒闭）感谢微博演出～ （倒闭）最终还是承担了所有～ 感谢美丽的城市杭州～ 也感谢杭州这座城市所有的职能部门的大力支持，感谢他们保障我们这次演出的顺利进行，也感谢我们志愿者们好不好？感谢现场所有台前幕后的工作人员～ 还有最最最重要的重磅嘉宾，就是每一个来自现场的你～ 包括看台的朋友们谢谢你们来～ 刚刚演唱的不想睡是卡布的晚安曲，演唱完后卡布就会下麦，接下来这首歌是周深的晚安曲，叫做我以渺小爱你～ 在此之前，我们来大合照吧～ 中间的朋友～ 我发现后面照片我脑袋会挡住几个人，我尽量就是～ 321～ 好，我们左边这边的朋友～ 321～ 谢谢大家，我们抓住了夏天尾巴，一起创造了很多夏天的回忆，谢谢你们～ 这边的朋友～ 321～ 还有就是那边的朋友～ 好没有默契啊哈哈哈～ 好，来洛～ 321～ 然后包括这边一点的哦～ 321～ 那边的朋友～ 321～ 很开心出道十年，我们见面啦～ 这边哦～ 321～ 这边的朋友，你们好～ 321～ 谢谢我们的摄像老师，再次掌声谢谢每一个你～ 接下来这首歌是周深的晚安曲，谢谢你们看到了我，谢谢你们在人群中，再渺小你们都看到了我，也谢谢你们照亮了我，我以渺小爱你，希望你能感受到这份渺小的温暖，好吗？

🎵【我以渺小爱你】不要嫌我的力量不够大哦～ 因为你们力量非常强大～ 谢谢～ 谢谢你们～ 我们做到啦～ 我会努力在舞台上多唱几年的，好吗？～ 谢谢你们～ 我们一定会再次相遇的～ 

## Part5 
🎵【起风了】大家好，我是歌手周深，谢谢你们还在～ 你们好吗～ 谢谢你们～ 谢谢你们，用爱吹起了这阵风，谢谢你们～ 谢谢～ 

🎵【大鱼】（唱：倒流回最初的相遇～ ）我们相遇啦～ 谢谢大家～ 
还想耽误大家一点时间唱一首专辑里的歌好吗？在唱这首歌之前呢我们会有个少管我的互动，大家知道吗？大家听过这首歌吗？我们试一下哦～ 嘿（少管我【无手势？】），如果这也算听过的话～ 哈哈～ 我们有一个少管我的特定姿势，嘿，少管我～ 但是做这个动作的时候小心不要打到前面的头，看台的朋友记住这个动作了吗？来我们全场来一下哦～ 嘿，少管我～ 没错，少管我这三个字呢，是让大家以一个乐观的心态去看待所有问题，不要争吵不要争执，这是都是对少管我三个字的刻板印象，所以我希望我们可以，就是看待所有烦心事的时候都有一个更乐观心态去看待它，就轻轻的说一句，嘿少管我，然后自己对自己负责，去向那个更好的自己向前出发好吗？一样的，全场倒数5个数字，如果摄像机捕捉到你的话，就要喊出你最大音量喊出这句嘿少管我这几个字让全场都能听到好吗？全场倒数五个数字，54321～ 啊啊啊～ 这是在哪里～ （唱：在哪里～ ）hello～ 你手拿着他是怎么想的，你喊出的是少管我这三个字是吗？应该怎么称呼你？布？布星星？星星？就是星星？你是哪里来的？宁波来的？掌声欢迎宁波的朋友来杭州玩～ 你什么时候听我唱歌的啊？大概几年前？几几年？四年前？十年前？后边的朋友厉害了～ 四年前，你第一次听我的歌是？没想到有这么难的题目吧？还对了，你好意思说～ 那就用声音喊出最大声音跟我说少管我～ 321～ 棒棒棒～ 谢谢你～ 谢谢星星～ 我们再来一位吧，全场～ 54321～ 停～ 哎呦～ hello？你拍我的时候开美颜了吗？应该怎么？前面后面？哦，是后面那位，对不起～ 应该怎么称呼你～ （生米）生米～ 你是聪明的～ 那你要代替全场喊出最大声这声少管我哦，好，321～ （少管我）特别棒，我们全场再来一次，好～ 321～ 看台的声音大一点，再来一次，321～ 谢谢你们～ 向更好的自己出发吧～ 芜湖～ 

🎵【少管我】希望大家能够喜欢新专辑反深代词～ 全场～ 全场，321～ （嘿，少管我）太棒啦～ 杭州的朋友，你们太棒啦～ 全场～ 全场，321～ 谢谢你们来看我～ 谢谢～ 谢谢你～ 东西不要掉了好吗～ 谢谢你们～ 我们一定会再次相遇的对不对？54321～ 我爱你们～ 手机不要掉了，证件不要掉了，好好照顾好自己～ 我们在这里发射出的光线，在宇宙另一端还会再次相遇的，所以这次的相遇并不是结束，好好照顾好自己～ 谢谢～ 54321～ 谢谢你们～ 54321～ 让我们下次相遇之前，好好照顾好自己，ByeBye～ 
