# 2024.09.22北京场 {#beijing-20240922}

## Part1 
🎵【借过一下】北京的朋友们，你们好吗～ 

🎵【Monsters】【化身孤岛的鲸】北京的朋友们，你们好吗？（米：好）愿意跟我一起唱吗？（米：愿意）到你们洛～ 看台的朋友，大声点～ 到你们～ 看台的朋友～  （深：我想给你能奔跑的岸头）（米：没有墙头）你们猜我信不信？看台的朋友猜我信不信（深：无论你们有多少个墙头，你们依然是国王和王后）
北京的朋友，你们好吗？（米：好）大家好，我是歌手周深，我们又在鸟巢相见啦，谢谢大家来到 9.29 赫兹巡回演唱会，演唱会为什么叫做 9.29 赫兹呢？是因为人类可以听到的声音是 20 赫兹到2万赫兹之间。然后，我自己认为我是一个比较没有那么容易被接受或者是被喜欢的歌手，所以我觉得自己是一个很渺小的歌手，甚至很有可能没有办法被听见。但是全世界最善良、最美好、最具有善意的你们听到了我，所以我们在这里相聚了，谢谢每一个生米，谢谢每一个听到我的人。谢谢你们让我不害怕黑暗，因为我发现哪怕我一个人走在暗巷的时候，你们依然是我的光亮。也希望歌手周深加油，能够成为你们的光亮，好吗？（米：好）大家掌声欢迎钱雷老师。

🎵【光亮】你们好吗～ 【深深逗雷哥】（深：最无畏的你）（雷哥起身）（深：光亮你自己）谢谢雷哥（雷哥起身准备下班）（深：最无畏的你～ ）掌声感谢雷哥（雷哥再次准备下班）（光亮你自己）

🎵【若梦】每次遇见你们都像是一场梦一样～ （深深戏精表演弹琴）等一下用最大的声音跟我一起合唱哦，你们（唱的）是最好听的版本～ 到你们洛，（米：往事流转，在你眼眸）大声一点，看台的朋友～ 你们太棒啦～ 大声～ （米：往事流转，在你眼眸）看台的朋友～ 全场最大声～ （深：唯愿你你你你….你你你能得到拯救）

🎵【浮光】跟我一起～ 在这人世间恍惚三万天当中，遇见你就是最美的浮光～ 

## Part2 
🎵【请我不改】全场嗨起来～ 看台的朋友～ 
大家好，我还是周深。你们对这样的风格的周深感觉到陌生吗？不陌生。那你不会是听了周深的新专辑反深代词吧？谢谢谢谢，谢谢我的生米们，然后也介绍一下我自己的新专辑叫做反深代词，刚才那首歌就是反深代词里面的歌叫请我不改，他说的是因为最近几年有个词很有热度，叫做PUA，就很多时候人会发现诶，好像自己一直处在一个非常低气压的状态，但是好像大家会忘记的另外一种状态就是不停的自我苛责，自我否定，就一种自我 PUA 的状态，所以就像刚才请我不改写的一样。当你发现诶，好像你的生活当中无法喘息的时候，你发现追兵与逃兵居然都是你自己，所以希望你可以认清自己，爱自己，做自己，有的时候也要放过自己好不好？那我们来看一下反深代词当中还有什么样的周深吧～ 

🎵【蜃楼】【警报】 谢谢大家，谢谢，谢谢～ 
大家好，我是歌手周深，你们好吗？看台的朋友你们好吗？（好）刚才演唱的三首歌都是新专辑反深代词里面的歌曲，希望大家可以去听一下这张新专辑，如果不愿意的话，求求你们了，大家去听一下这张专辑。里面一共是我的十二个化身，果然我们南方人的前后鼻音比较难分，12 个化身会在 200 年后，刚才的第一首歌是请我不改，就是希望自己放过自己，然后刚才第二首叫做蜃楼，他是由执念组成的一个蜃楼，有的人被困在蜃楼当中，他觉得很痛苦，但有的人被困在比较好的执念当中，他就会变得越来越好。但无论怎么样都不是错，所以这个世界上没有就是要么就是对，要么就是错的这样的答案。然后刚才那首叫做警报，是送给每一个，就是想要照顾所有的人，想要照顾每一个朋友、每个环境存在的每一个人，哪怕是陌生人的人，但是最后却偏偏忘记照顾好自己的那个人，所以希望如果你是这样人的话，可以听到刚才的那一首警报，然后开始好好爱自己好吗？其实我也有就有看到，就说周深在演唱会是不是没有话说了，就是不停的在反复让大家一定要好好的爱自己，好好照顾好自己。我后面也想了一下，其实不是，因为我认为我们能够相遇在这里，我们一定多多少少有一些部分是比较相似的，而我其实，我认为我是一个不太那么会好好爱自己的人，而在我自己经历过那么多年的成长，包括出道十周年之后，我会发现所有的苦痛都来不及，就是都不及，那个就是自己没有好好照顾好自己带来的那个苦痛更痛。所以我觉得只要你开始好好爱自己，所有的美好都会慢慢慢慢向你奔跑而来，好吗？（米：好）有没有人觉得自己好像有一部分跟我很相似的？（米：有）我好像没有听到看台朋友们的声音，有吗？我也很开心，在很多的综艺舞台上也有不一样的周深，那么这首歌是长什么样子的呢？

🎵【天堂岛之歌】谢谢大家～ 
有没有是通过刚才那首歌认识我的呀？如果没有的话，你们会刚才听完那首歌之后感到害怕吗？（米：不会）大家胆子挺大的。前面，告诉他一个小秘密，就前面那一段，（一个、两个、三个小朋友）也是，我自己就是躲在被窝里，然后自己录的那一段。好，那接下来这首歌我是需要你们跟我一起大声合唱，你们准备好了吗？它可以说是我们 9.29 赫兹巡回演唱会里面的一道考题。它是一个童话故事，他的主人翁的名字非常难念，我们随机考一下，看台的朋友，他的主人翁叫达拉，（米：达拉崩吧斑得贝迪卜多比鲁翁）离我近一点的朋友，题目就比较难了，你们，昨天我考的时候公主的名字没有难倒，请问他们回到的那个城市叫做？我还不信，我还考不到你们，那个城市的名字我都记不得。那等一下跟我一起大声唱这首达拉崩吧好吗？（米：好）

🎵【达啦崩吧】大家嗨起来，看台的朋友～ 现在你们准备好了吗？现在到你们的时候了哟，想想他的名字叫什么，拯救了谁呢？于是～ （米：达拉崩吧斑得贝迪卜多比鲁翁）砍向～ 然后～ 咬了～ 大声点，最后～ 看台的朋友～ 再来一遍哦，他的名字叫达拉（米：达拉崩吧斑得贝迪卜多比鲁翁）砍向昆图（米：昆图库塔卡提考特苏瓦西拉松）这么爱念（深：要念你来念吧～ ）谢谢你们～ 

好像听说在演唱会当中指向哪里，哪里就会有欢呼声，是这样的吗？真的是这样的吗？我不相信诶，那如果是指向看台也会有声音吗？那如果是那边的看台呢，我们今天有近6万的观众，那如果我是这样的话呢，那我想听一下近6万的观众在鸟巢喊钱雷的名字是什么样的？321，（米：钱雷）感觉像钱磊老师欠了大家什么。哈哈哈，我觉得就大家都会夸我很有仪式感，我觉得钱磊老师也是最有仪式感的人，毕竟来了鸟巢，头上还顶了一个鸟巢来了，哈哈哈，给大家打个招呼吧。（钱雷：大家好）雷哥，他的名字大家可能比较陌生，他的样子大家可能更陌生，但他的作品大家很熟悉，来唱一两首吧。（钱雷：看你飞远去，哈哈哈）（深：祝你踏过千重浪，能留在）（米：能留在爱人的身旁）停，不能唱太多，哈哈哈，很多很多，（深：而我将爱你所爱的）（米：爱你所爱的人间，愿你所愿的笑颜）停，好，谢谢大家的合作。哈哈哈来，你来到鸟巢了，你总要给大家正儿八经多说一点照顾，不要说自己内向，我也很内向。（钱雷：呃，我觉得，鸟巢一定要来，因为）是第几次来到鸟巢？（钱雷：第一次吧）我也是一次在鸟巢开演唱会，所以要谢谢每一个到来的你们，一句话，你此时此刻最想说什么？（钱雷沉默）谢谢，那接下来这首歌希望大家喜欢，我经常说雷哥写歌太难了，你是人吗？就现在就故意这样做的，这首歌叫做人是_哈哈哈～ 

🎵【人是_】没弹好，重来，重来一遍吧，来，321，哈哈哈，好好，我错了我错了我错了，好好唱歌，人是_，希望大家喜欢～ 一起～ （弹指间湮没我～ ）掌声送给雷哥～ 我爱你们～ 

## Part3 
鸟巢的朋友们你们好，大家有找到我在哪里吗？话说我第一次来到北京的印象就是，我发现，虽然网上有个梗，都说，哈哈，北京人都是鲨鱼，有人知道这个梗吗？但是在我心中我觉得北京人每个人都是指南针，我第一次来到北京，然后就北京人特别的热情，就是你去求助的话，他们都会非常热心地帮助你。我就说，诶，请问一下先生这里怎么走？然后他说这个地方很近，你前面走 10 米，向西转，然后再走 10 米再向东走，我在想哪里是西啊？然后，然后就那个时候也没有手机，然后手机也没有定位什么的，就完全都不会。然后我的妈妈手机它也没有定位，我们就不知道该怎么走，然后我们就又问了个朋友，他说，噢，很好走，你前面就往西走了 10 米之后再往东转，然后干嘛？哪里是西啊？直到现在我到北京我都不敢问路，因为我真的不知道哪里是西边，哪里是东边，因为我们就是真的没有这个，为什么大家不用左右呢？所以也会有北京朋友有这样的困扰吗？我听到了非常大的声音说没有，好的，我输了，对不起。接下来这首歌非常的温暖，现在天气越来越凉了，大家一定要记得多添加衣服好不好？大家有穿够衣服吗？比如我，像我一样加了秋衣？接下来两首歌也是非常非常温暖的两首歌，它温暖的就像秋衣一样，哈哈哈，希望你们喜欢。然后你们听完我弹奏钢琴之后就会发现，哇，刚才到底是哪里来的信心去说钱雷弹的钢琴弹得不好，哈哈哈，总之希望你们喜欢～ 

🎵【My Only + Rubia】我爱你们～ 谢谢你们～ 

🎵【小美满】大家跟我一起大声唱好吗？（米：好）你们（唱的）是最好听的版本哦～ 看台的朋友，大声点哦～ 全场～ 你们唱得太好听啦，再大声一点哦～ 大声点～ 到你们了，大声点～ 大声点～ 谢谢你们～ 每一次一听小美满我都觉得特别的幸福，我感觉所有的愿望都会实现的，那不如我们就在这首歌当中许一个愿望，就像我这样闭上眼睛，然后默默想好心中的愿望，然后 321， 愿望就会挂在这棵许愿树上，所以现在在现场的你，无论什么年龄，无论什么职业，就在此刻闭上眼睛，我们默默地许一个愿望吧，闭上眼睛，闭上眼睛，许愿啦，听话，想想心中的愿望，我们有一个要求，就是只能够许关于自己的愿望哦。想一想有多久没有好好的问候一下自己了，多久没有好好关心自己啦，抱一抱自己吧。321， 睁开眼睛哇，你们的愿望都会被听见的，都会实现的，继续加油好吗？（米：）你们是最美好的存在～ 到你们～ 你们实在是太美好了～ 🎵【好好生活就是美好生活】（深：新的一天我们一定）（米：好好）好好爱自己，是一切美好的开始，记住好吗～ 

🎵【花开忘忧】（米：你好啊）你好啊～ 北京的朋友，我们来你们家玩喽，来看你们啦～ 全场跟我一起好吗～ 大声点～ 我们的思念，那些离开的人一定听得见，对不对～ （米：对）我以前以为我一个人声音太小了，他肯定听不见，但是因为遇到你们，他们一定听得见，对不对？（米：对）花开忘忧，愿你无忧，花开忘忧，（米：愿你无忧）谢谢你们～ 
我非常感谢你们，其实我是一个比较没有安全感的人，所以一开始也会比较害怕在大家面前展现太多面的我。（深深换衣服，米尖叫）不用惊叫，我有秋衣。但是因为遇到你们之后，我就愿意去袒露更多的心声，就像刚才弹钢琴一样，我知道我一定弹得非常的不完美，甚至很有可能比很多小朋友谈的都不好。但是我想告诉你们的是，只要你想学一个技能，从任何时候开始都是可以的，因为永远有那样一个温暖的爱，它会接纳你每一个碎片，哪怕它是不完美的碎片，好吗？（米：好）因为我一定会接起你的每一个碎片，谢谢你们～ 
我第一次听到什么叫做唱歌，就是听到了邓丽君女士的歌声，所以我也希望自己可以成为像她这样的歌手。他的每首歌当中有很多人的记忆胶囊，就感觉里面存放了很多故事在里面。小朋友你肯定没有听过这些歌，但是你可以听一下，就是，嗯，爸爸辈、妈妈辈，或者是爷爷奶奶辈，他们听的歌声会是怎么样的感觉呢？有人会唱这些歌吗？那等一下跟我一起唱好吗？（米：好）

🎵【邓丽君歌单组曲】（米：宝贝）宝你个头🎵【千言万语】（深：那天起，你对我说，永远的爱着我）骗子（深：千言和万语，随浮云掠过）受伤了～ 🎵【在水一方】大家跟我一起唱好吗～ 全场～ 🎵【路边的野花不要采】墙头很多的人，可给我听好了，你们说（深：路边的野花）怎么样（米：你不要采）记住了啊～ 你们会忘记我吗？（米：不会）我只在乎你你你你你🎵【我只在乎你】大声点～ 看台的朋友，大声点～ 请记住歌手周深好吗～ （米：好）

## Part4 
【谢谢北京谢谢你VCR】

谢谢你，谢谢北京，谢谢每一个听到我给我善意的你，谢谢你，谢谢你们看到了我。大家 08 年的时候在干什么呀？好的，我没有听清楚，但是我印象很深的是 08 年的时候，我们每个人肯定都在期待着看奥运会的开幕式，我是在贵阳的我们一个广场上的一个公众，公共大屏上一起看的，跟很多朋友们和小学同学们，哎呀，小学同学们。然后当时我就觉得，哎呀，我要是能够在北京欢迎你这首歌当中唱一句，我都觉得可是太幸福的事了。但是那个时候的我依然还是那个写不出以我的梦想为题目的作文的那个周深，因为他不知道要成为一个什么样的人。但是每天那个周深还是好好的去做好每一件事情，向前去行进着，向前去追逐着，突然就到了 16 年之后，周深站在了鸟巢跟大家相遇了，所以我特别兴奋能够在鸟巢跟大家一起唱起这首歌，北京欢迎你，你们愿意跟我一起唱吗？（米：愿意）

🎵【北京欢迎你】大声点～ 全场～ 大声点～ 谢谢你们，而且我们今天的音响总监也是当年奥运会开幕式的音响师金少刚，我们继续向前冲，有勇气就会有奇迹，好不好？（米：好）大声点～ 看台的朋友～ 再大声点～ （北京欢迎你～ ）

🎵【灯火里的中国】然后就有一天，这个普通的男孩第一次登上了春晚～ 全场一起～ （灯火里的中国，青春婀娜～ ）一起～ 谢谢大家～ 
你们能够让一个非常普通的男孩子慢慢地去靠近他的梦想，是你们创造出来的奇迹，要相信自己好不好？（米：好）再次掌声给我们的金少刚老师，鸟巢我们来了，也希望我们可以创造更多奇迹时刻～ 

🎵【奇迹时刻】大家嗨起来～ 看台的朋友～ 大家好～ 【魔术时间】小小魔术师又来了哟，大家掌声再次有请雷哥～ 而且还有哦，321～ 谢谢大家～ 
每次一到魔术的段落，教我魔术的唐老师都在下面，哎呀，哈哈，但是在反深代词当中，还想再拜托大家听一下里面的歌好不好？里面有一个快乐密码，它叫做，wala li longla，没错，只要喊起这个密码，它就会给你带来无限的快乐。我们等一下试一下好不好？来试一下，wala，看台的朋友，wala li ，wala li long，wala li longla，希望快乐永远在你身边～ 

🎵【wala li longla】全场嗨起来～ 哎呀，我一个人的声音太小了，你们愿意跟我一起大声喊起这个快乐密码吗？看台的朋友也愿意吗？那么等一下全场跟我一起好吗？wala，wala li ……大声点～ 看台的～ 看台的～ 全场～ 全场，321～ 我还想再听一次，321～ （米：wala li longla）你们一定是全世界最快乐的人，谢谢大家～ 
那接下来这首歌非常的巧妙，在这个地方唱起来。鸟巢大家都知道是08年奥运会开幕式的地方，那这首歌在今年奥运会也被剪进了很多我们奥运健儿们的精彩瞬间，当他的背景音乐，我觉得我们每个人的人生也是不停地在向前冒险，向前探索，但是我们每个人一定可以收获属于我们自己的璀璨的，对不对？你们可以创造奇迹，把一个非常普通的男孩周深送到那么多那么多那么大的舞台，周深可以做到的，你们一定也可以向前冲吧，璀璨冒险人～ 

🎵【璀璨冒险人】跟我一起好吗（他们说要越过前方风沙必须低着头……）大声点～ 全场～ 大声点～ （米：还想要继续吗）要～ 看台的～ 不要害怕自己不完美，继续向前冲好不好？（米：好）

🎵【点歌环节】现在到了我们 9.29 赫兹巡回演唱会的点歌时间啦。哇，你好漂亮，唔，你们都好漂亮啊，谢谢你们。全场帮我倒数五个数字好不好？（米：好）5（米：4321）他是，你，感觉，感觉从你的脸的表情不是很开心。哈哈哈，在这里。你好，在哪里啊？你好，怎么称呼您？（吴京润）有没有小名哦？胡京瑞？（吴）吴京瑞？（润）吴京润（对）一般怎么称呼你，都是直呼大名吗？也不是吧（京润）哈哈哈，好，京润朋友，您是来自哪里的朋友？（黑龙江）黑龙江的，哇哦，那我们全场近6万的朋友欢迎黑龙江的朋友京润，（谢谢，谢谢深深），也要谢谢大家，（谢谢大家），谢谢哪些人？（现场所有的朋友们，谢谢）现场是哪里？（鸟巢演唱会所有的朋友们，谢谢你们）谁谢谢鸟巢现场所有的朋友们，（谢谢周深！）什么时候开始听我的歌的呀？（好久好久）好久（16 年），哦第六年了，谢谢你。（16年） 16 年的时候，很久了耶，（这是我第一次看演唱会），谢谢谢谢谢谢，现场有没有跟京润一样是第一次开演唱会的？那有没有谁是第一次来到鸟巢的？哇，这么多朋友，谢谢你们把我带到了这么多可能的舞台，谢谢你们。请问一下您多大呢？（29）那我们差不多是同辈的，嗯，笑这么大声是什么意思？也就是说，好吧，你上面有没有喜欢听的歌？舞台这边就是一些，就是大家从舞台上认识我的，比如像我刚出道的舞台啊，天赐的声音上面啊，或者是像蒙面唱将里面的歌，然后录音棚这边就是我自己的歌曲，然后中间是返场，是在我们 9.29 Hz点歌中间出现的两首歌，可它爱着这世界和随风，你会比较偏向哪边？他的眼睛已经很明确，偏向的是舞台这边。（是的）你第一次听我的歌是哪首？（欢颜）你不会是等一下，你不会是你哦。哎呦，（有可能会有反转哦）现在的朋友们越来越难聊天啦，好的好的，那来吧，你想为我们 9.29 赫兹巡回演唱会北京站鸟巢第二场选择？（孤独的牧羊人）哇，你有很多惊喜啊，好，谢谢京润，谢谢（谢谢）谢谢你，这首歌有点压力啊，那我们就试试吧～ 

🎵【孤独的牧羊人】（深深看了眼观众，歌曲提词器太快，没跟上，哈哈哈哈）对不起，再来一下，大家就当没有发生过，好 321 ，京润，起来陪我演一下这段，谢谢京润～ 你们看那边～ 哦，我这么漂亮的衣服都被呛到了～ 哎呦，有好多小朋友哦～ 谢谢～ 
全场帮我再倒数五个数字，5，（米：4321）又是一位看起来好像不是很开心的，我们的点歌太真实了，您在哪里？噢，在那里对不对？哈喽，给大家打个招呼。（一位61岁坐轮椅来的阿姨）哦哦哦哦，对不起，对不起，哎，如果不太方便可以坐着的，没事的，我们可以坐着聊，我也可以坐着，（没事，站着吧）已经站着了。好了，那怎么称呼您？（你好，我叫龚金英）龚金央？龚金央？（对）准确的找到了我这个南方人最难发的两个音，哈哈哈，龚金英，好，应该怎么称呼您更亲切一点呢？（嗯，你叫我龚阿姨吧）龚阿姨好，（深深你好）您好，可以问一下您今年的年纪吗？
（我今年61）好巧啊，因为昨天我们也有一位 61 的朋友，您是？您应该是来自北京当地的吧？（对）哎呦，你看我这耳朵还挺好使儿。您是什么时候开始听我唱歌的啊？（应该是在 17 年， 18 年那会儿）您听到的第一首歌是大鱼耶，谢谢谢谢。旁边这位陪您来的是我的儿子，应该怎么称呼他呀？（他叫邵维）让他给大家打个招呼，咱们用麦克打招呼，（大家好）声音太大了，震耳欲聋了。邵维，您好，好，那您看一下您想听哪首歌呢？（漂洋过海来看你）谢谢，谢谢，谢谢您，谢谢，谢谢龚阿姨，谢谢谢谢，谢谢。好，那希望您能喜欢我唱我演唱的这首歌曲，漂洋过海来看你，也是非常感动的一首歌，因为，是不是的确有很多人也是漂洋过海来看我？我有看到，有从澳大利亚来的，谢谢谢谢谢谢。这是我在舞台上唱的一首歌曲，希望大家能够喜欢这首芒芒的漂洋过海来看你，会唱的跟我一起唱好吗？

🎵【漂洋过海来看你】一起～ （陌生的城市啊～ ）（多盼能送去千里，直到山穷水尽）我真的很希望（一生和你相依）我还有看到从北美来的出名，谢谢，无论你从哪里来，谢谢你来看我～ 

🎵【不想睡】你们好吗～ 一起～ （不想睡，我要陪你一整夜）谢谢你们，你们发出的光芒，的光子会在宇宙的另外一端，很多年，很多年之后它会相遇，我们就又一次见面啦，谢谢你们～ 全场～ 大声点～ 到你们～ （lalalalalalalala）和你们相遇真的太美好了，谢谢大家，大家今天玩得开心吗？一定要用这段记忆当做是一颗糖好好的保存起来，当你需要力量的时候，希望这一颗糖能够给你力量好不好？因为它一定是我生命当中最重要的那一份甜份，谢谢你们～ 
我们也要谢谢很多很多为我们付出，让我们很好相遇的人，好不好？（米：好）感谢场地支持，国家体育场鸟巢，我喊鸟巢，然后我们一起喊我们来了，好不好？鸟巢（米：我们来了），你们真的是最棒的。要感谢本次巡演的全程主办，北京时代立方文化传播有限公司。感谢演唱会制作单位必应，感谢我们的总导演周佑洋，庄惟惞，感谢我们的音响总监金少刚，谢谢，感谢我们的音乐总监龙隆老师，以及感谢我们所有的乐手老师们，以及我们的合唱老师们，谢谢大家，以及要感谢我们今天的钱雷老师，虽然我也没有什么给他说话的机会，但是我替他谢谢大家啊。感谢我们的舞蹈团队 SDT show Pro，感谢服装团队设计师劳伦斯许工作室，时装品牌 windowsen，音响工程南京奥斯泰，感谢我们的调音团队悦耳工作室，大家听到我的声音还悦耳吗？谢谢我们的硬体工程北京立超舞台集团。感谢周深工作室的小伙伴们，你们喊的比我唱歌的声音还大，我吃醋了，我走了。我代表周深工作室的小伙伴们，谢谢大家，我们还会继续努力的。感谢微博，感谢微博音乐，感谢微博演出。感谢我们最美的北京，感谢北京的公安、文化、消防、应急、奥管委等所有职能部门的大力支持，保障我们演出的顺利进行，大家感谢他们的掌声再热烈点，以及感谢我们所有现场，所有台前幕后的工作人员，感谢我们现场的安保团队们，也要感谢我们非常辛苦的志愿者们，当然最重要的是要感谢世间最美好，每一个都充满善意的来到现场的你。因为真的金少刚老师每一次都跟我说，就是你真的要好好感谢你的观众，因为你拥有最好的最棒的观众，谢谢你们。那我们来合照吧。来 321， 这边的朋友，321 ，这边的朋友，哇，还有越南的朋友，321，看台的朋友，我来了。（米：加油加油）你们会让我觉得我在为了明年的奥运会在做准备，哈哈，来 321， 这边的朋友，321，那边的朋友，我来啦，哎呀，好累呀，来我们拍照，休息一秒，321，这边的朋友，你们好，321，谢谢大家～ 
刚才的不想睡，是卡布的晚安曲，为什么是卡布？卡布是我在，大家知道有个歌手叫周深之前，我在网上自己唱歌的名字叫卡布。那现在周深有一首他自己的晚安曲，它叫我以渺小爱你，谢谢你们看到了人群当中最渺小的我，谢谢你们～ 

🎵【我以渺小爱你】我不知道自己还能唱多久，我也不知道你听过我多少首歌，但是无论你是不是生米，你只要听到我，你就给了我非常大的善意，很荣幸可以在你们的人生当中出现，哪怕只有 10 秒副歌的时间，我很渺小，我的力量也没有那么大，谢谢你们看到了渺小的我，也谢谢你们给我不朽的爱（我以渺小爱你，同行的旅程，我以短暂爱你，不朽的旅程）谢谢你们～ 好好照顾好自己～ 

## Part5 
🎵【起风了】谢谢你们来，谢谢你们还在～ 以爱之名，你还愿意吗？（米：愿意）我真的好幸福啊～ 你们也一定要幸福好吗？

🎵【大鱼】谢谢大家，我每次唱到这里，我心中只有四个字，就每次跟你们的见面我都觉得自己何德何能，谢谢你们～ 
我们一起由当年的奥运会开幕式的音响师金少刚老师，然后钓这条鱼的团队，也是当年开幕式的威亚团队，大家掌声送给老师们，也要谢谢我们所有为我们创造这一场非常幸福的聚会的老师们，大家掌声再热烈一点，朋友们，这是鸟巢啊，谢谢大家，那我还想再耽误大家一点点时间，还有一首歌是反深代词里面的歌叫少管我，它听起来也许有一点点争议，他感觉像吵架，但是想要告诉大家，像这首歌一样要轻松活泼，我们要对自己负责，我们要知道怎样去成为更好的自己，因为我们的梦想一定会实现，不要害怕中间任何的一些挫败或者失败，好吗？当在不打扰别人的前提下，如果别人来影响你的节奏，我们就轻松说一句，嘿，少管我好吗？我们还是会用相机捕捉两位朋友，然后让他喊出最大的声音，全场倒数五个数， 5（米：4321） 停，您好，来到了最难的这个环节，你叫什么名字？何伊，Joey，oh，joey，欢迎joey，你是来自哪里的朋友？上海，好的，用你最大的声音，让我们全场近6万的人能听到你的嘿，少管我，321，谢谢你～ 全场的朋友，我想听到你们跟我一起，嘿，少管我好吗，321，（米：嘿，少管我）所有的不开心都会离你而去的～ 

🎵【少管我】谢谢你们，我忘了说一句话，我爱你们～ 全场～ 321～ 全场，54321～ 看台的朋友，等下要大声点哦～ 54321～ 全场～ 321～ 全场～ 54321～ 谢谢你们，注意安全，证件不要掉了，手机不要掉了，一定要平平安安的到家好不好？我们一定会再次相遇的，看台的朋友，谢谢你们，在我们相遇之前替我好好照顾好自己，答应我好不好？（米：好）54321，谢谢你们～ 