
# 我是如何一步一步掉入米缸的 {#appendixC}

*@my-journey*


&emsp;&emsp;已经很久很久没有这么正式的想写点东西了，但是七夕场演唱会给我提供的情绪价值太大了，让我情不自禁的想写点什么，这就是传说中的“戒断反应”吗？那就说说我是如何一步步掉入米缸的吧。

&emsp;&emsp;正如我小红书名称和简介写的，我的老婆是生米，所以要论第一个因素肯定是我老婆，但根本因素还是因为周深，这几年来陪着我老婆追周深的点滴，也让我一点一滴的认识了周深，了解了周深，看到了他的努力，感受到了他的真诚与谦逊，折服于他的声音，欣赏他的风趣，他真的值得！

&emsp;&emsp;好了，步入正题，我是如何一步步掉入米缸的？时间回溯到2020年，研究生毕业一年时间，那时跟我老婆（那时还是女朋友）在一起三年多了，因为一些原因，我跟我老婆开始了两年多的异地生活（当时也没想过会长达两年）。加上口罩原因，我们见面的机会并不多，但是我们几乎每天都会视频，异地过的情侣可能体会过，时间久了可能没啥话题聊，所以那时候周深成为了我们话题的一部分，她会跟我分享一些周深的事情，周深的一些舞台，还有一些有趣的采访，那时候我的感受就是她跟我分享的时候好开心啊～对周深还没啥感受～

&emsp;&emsp;再后来，女朋友给我推荐青春环游记第二季，也是通过这个综艺，让我对周深有个更立体的了解，了解到了深深有趣的一面，给我带来了很多的欢乐，也同样丰富了跟我异地女友视频沟通的话题。

&emsp;&emsp;时间来到21年，5月深圳南山流行音乐节，女朋友第一次见到了周深，我那时是在场馆外面等候，记得那时候票是免费预约的，我代她去领的票。再到10月份，我们一起到成都参加“潮拜72小时”音乐节，那是我听到的第一次周深现场，那时候她在拍周深，我在拍她，那天也碰上了下雨，雨中瑟瑟发抖等了一天，也是度过了难忘的一天。结束短暂的见面，我们又继续异地～

&emsp;&emsp;有了陪女友追周深现场的经历，她就开始了给我买周深同款衣服了，那我自然是开心啊，毕竟有新衣服穿，哈哈哈～后来我也分享过女友给我买的那些周深同款的衣服，收获了很多其他生米有趣的评论和点赞祝福，哈哈哈哈～再后来女朋友给我发了很多深深表情包，我也存下来了用来丰富我们的聊天！

&emsp;&emsp;时间再来到22年，这年对我们来说是很重要的一年，因为这年我们结婚啦，啦啦啦啦～婚礼的大大小小事情都是我们自己操办，那婚礼的歌单自然得是周深的了，所以在找了一些小红书帖子后，下载了很多首周深的歌作为婚礼歌单（歌单在22年10月13日小红书分享过），毋庸置疑，My Only作为我求婚的歌曲和婚礼新娘入场的歌曲。所以，演唱会每次唱My Only时候，我脑中都是我求婚和婚礼时我老婆向我走来画面～感谢周深！

&emsp;&emsp;23年，我们终于结束了异地，一起来到了成都。然后就是陪老婆一起看跑男了，继续了解到深深有趣的一面，有趣的灵魂，从他身上让我想到另外一个非常好的朋友，也是拥有有趣的灵魂，反应超快又有时候点很奇特，哈哈哈哈，拥有这种朋友真的很开心！819没能陪老婆去北京，那时候我还没有要去看深深演唱会的欲望。10月陪老婆去了常州音乐节，穿着深深同款背带裤，我在别人眼中已然是一个生米了。

&emsp;&emsp;但有别于前面音乐节现场的感受，演唱会给我带来的冲击是音乐节没法比的。老婆自己去看了518上海场，深圳的时候她问我要不要一起去看，当时我还是处于看不看都行的状态。但我在异地的时候说过要带她一起去内场看周深演唱会，考虑成都场我不能陪老婆去。于是决定陪老婆一起去看深圳场，毕竟是周深第一个体育场演唱会。

&emsp;&emsp;谁知，看完一场后，根本停不下来啊，现场感受太好了，哪怕深圳场下雨了，丝毫不影响体验，反而更加难忘！回想过来，这时候我已经愿意花时间在周深身上了，愿意花时间整理歌单并不断优化格式，愿意第一时间熬夜整理成都场talking文字版。也有了后面一起去贵阳，去深深家乡看演唱会，花开忘忧深深说谢谢你们陪我一起回家。深深和生米们真的双向奔赴，希望深深知道，现在大家都是可以自豪的说出来喜欢的歌手叫周深。剪贵阳场talking全程，发现他真的很真诚，现场鞠躬了很多次，在歌曲结束后会对舞蹈老师鞠躬表达感谢，歌曲中和歌曲结束会对三面观众鞠躬。满满的诚意我一边剪一边看在眼里。

&emsp;&emsp;最后再说下这次七夕南京场，在这时候已经对周深是很喜欢了，从过往的一个个细节上感受到了深深的善良与真诚，对每一个观众的用心和对生米的爱。而南京的两场演唱会则让我彻底沦陷了，他为生米做的点点滴滴都看在眼里，他说过很多次是生米治愈了他，是一个你你你你你你才得到拯救，是他的光亮，他说和生米合唱的若梦是最好听的版本，演唱会夸我们太棒了！他说我们都是发光的星星，他时刻让我们要先照顾好自己，先爱自己，让我们去肯定自己，为自己许愿，也许曾经某个时刻他怀疑过自己，但是生米让他坚信了他可以做自己，他值得被爱！他说遇到我们是他最大的小美满，他说我们是最好的生米，他说梦见的都是我们，他说爱我们（819深深感谢你唱我只在乎你他说的爱要大声说出来一直在我脑海中）。。。他还说了很多～演唱会现场，收获了感动，收获了喜悦。

&emsp;&emsp;言语无法完全表达出我的心情，但我也想对深深说那句：**你一直唱，我和我老婆一直在！**

              
       