# 9.29Hz巡回演唱会VCR {#appendix-vcr}

- [开场VCR](#opening-vcr)

- [反深代词VCR](#senself-vcr)

- [客服大门VCR](#close-door-vcr)

- [谢谢你VCR](#thank-you-vcr)

## 开场VCR {#opening-vcr}

赫兹指每秒声音波动的次数 

9.29Hz是一段人耳听不到 却能量极大的次声波 

就像从前的我 

无法被人听到

却因为有了你 

选择治愈 
 
便有了不同的意义

身陷沟壑之中 

总有人仰望星空 

只身浩瀚的宇宙 

感知生命的力量 

将日月 星辰 风雪都收在声音里 

那些在黑暗中的人 

也必定 看见光

欢迎来到9.29Hz 

一起找到生命中 

拥有同样波动 同样频率的你 

音乐只是我们相识的方式

我们的相聚才更有意义

## 反深代词VCR {#senself-vcr}

我听见了

你听见了吗

听见你偶尔感到挫折 有时面对失望

听见你一边崩溃一边咬牙坚持

却依然 对生命的热情

听见你明确的爱 真诚的爱 站在阳光下的坦荡

听见你努力让生命开出一朵朵美丽的花

我听见回声 来自山谷和你的心间

我听见希望 

我听见你

## 客服大门VCR {#close-door-vcr}

嗯？

怎么了？

就结束了？

演唱会最后一首歌？

那 各位拜拜喽?

不

那为什么要关门呢？

怎么关闭的？？

关的什么门？

哦，都忘了自己是关闭客服大门的门

哈哈哈，哦，对了

那我为什么会出现在这里呢

我知道了

我其实是...

通往幸福的我门

哇 呕

哈哈哈

好了好了 继续听歌吧

我先走喽

我是幸福的我门！

我是幸福的我门！

我是快乐的我门！


## 谢谢你VCR {#thank-you-vcr}

> （小朋友）谢谢爸爸妈妈，我爱你们  
> 
> （外卖员）谢谢你今天为我写下的好评  
> 
> （列车员）每一次的旅程都将充满未知的冒险和期待，感谢您乘坐本次列车  
> 
> （医生）治愈伤口的我也常常被你们治愈着，谢谢你们  
> 
> （白发夫妻）一路有你，迷迷糊糊的浪漫  
> 
> （打工人）谢谢自己，每一份付出都有回报  
> 
> （学生）我永远都记得你，我最亲密的伙伴  
> 
> （青年）谢谢青春，让我拥有生命中最美好的回忆  
> 
> （舞者）谢谢你的陪伴，让我在追梦的路上勇敢前行  
> 
> 谢谢你的关怀，我心存感激  
> 
> 你的帮助无异于雪中送炭，让我倍感温暖，谢谢你  
> 
> 谢谢你的每一份付出，都将成为我们前进的动力  
> 
> 谢谢你的关怀，感谢你的帮助，感谢你对我做的一切  
> 
> 谢谢你的歌声，给予我一路的陪伴  
> 
> 谢谢你的微笑，温暖了我冒险的旅程  
> 
> 你的善良和感慨，让我感到深深的敬意，谢谢你  

嗨

好久不见

你还好吗

我们一定是感受到了生活的善意

才有机会说一句谢谢

而当你听到我 

当你出现在这里 

当我遇见你 

这都是我感受到的 生活里最大的善意 

谢谢你来 

谢谢你愿意与我同频

也一定要记得替我照顾好你自己哦

我们一定都会好好的 

你要知道爱你的人 

一定 比你想象的多 

谢谢你 

谢谢____ 

谢谢你
