# 9.29Hz巡回演唱会歌曲歌词 {#appendix-song-lyric}

[借过一下](#I-will-go-my-way)

[Monsters](#Monsters)

[化身孤岛的鲸](#hua-shen-gu-dao-de-jing)

[光亮](#guangliang)
    
## 借过一下 {-#I-will-go-my-way}
[点击收听](https://y.qq.com/n/ryqq/songDetail/00446BOH0yUBXf)

***

周深

词：唐恬

曲：周以力

制作人/编曲：周以力

***

少年扬起脸庞 前往他的月亮

人们笑他狂妄 人怎可不一样

白衣过泥潭 怎敢说不染

但凡银两有价 谁能真潇洒

少年爬上城墙 去见他的月亮

破碎几次心脏 得来几句真相

市井或朝堂 四方皆如框

若你生来有刺 磨掉再入场

你们都是对的他说拜托

让开一下

让我大醉一场 殿堂之上

背闲诗两三章

让我穿白衣裳 过疯人巷

去泥潭捞月光

望大人们见谅 提点的话

我懂也不想装

世人寻黄金乡 我找月亮

何必同往

话谢过 路借过 你是你 我是我

话谢过 路借过 你是你 我是我

诚如先生所说 每颗心都有瑕

潇洒不是不怕 是愿付出代价

权衡利弊后 仍守对与错

谢过赐教的话 路借过一下

让我大醉一场 殿堂之上

背闲诗两三章

让我穿白衣裳 过疯人巷

去泥潭捞月光

望大人们见谅 提点的话

我懂也不想装

世人寻黄金乡 我找月亮

何必同往

话谢过 路借过 你是你 我是我

话谢过 路借过 你是你 我是我

白衣过泥潭 世故里浪漫

知心有所爱 不更改

人见过明暗 若天真犹在

当披上月光 走夜晚

## Monsters {-#Monsters}
[点击收听](https://y.qq.com/n/ryqq/songDetail/004IQQao12ptH0)

***

周深

词：Catherine Beatrice Cheadle/Mads Vathne Lervik/Bjarte Ludvigsen

曲：Catherine Beatrice Cheadle/Mads Vathne Lervik/Bjarte Ludvigsen

***

I see your monsters

I see your pain

Tell me your problems

I'll chase them away

I'll be your lighthouse

I'll make it okay

When I see your monsters

I'll stand there so brave

And chase them all away

In the dark we we

We stand apart we we

Never see that the things we need are staring right at us

You just want to hide hide hide

Never show your smile smile

Stand alone when you need someone

It's the hardest thing of all

That you see are the bad bad bad memories

Take your time you'll find me

I see your monsters

I see your pain

Tell me your problems

I'll chase them away

I'll be your lighthouse

I'll make it okay

When I see your monsters

I'll stand there so brave

And chase them all away

I can see the sky

Beautiful tonight

When you breathe why can't you see

The clouds are in your head

I would stay there

No need to fear

When you need to talk it out with someone you can trust

What you see are the bad bad bad memories

Take your time you'll find me

I see your monsters

I see your pain

Tell me your problems

I'll chase them away

I'll be your lighthouse

I'll make it okay

When I see your monsters

I'll stand there so brave

And chase them all away

You've got the chance to see the light

Even in the darkest night

And I will be here like you were for me

So just let me in

I see your monsters

I see your pain

Tell me your problems

I'll chase them away

I see your monsters

I see your pain

Tell me your problems

I'll chase them away

I'll be your lighthouse

I'll make it okay

When I see your monsters

I'll stand there so brave

I see your monsters

I see your pain

Tell me your problems

I'll chase them away

I'll be your lighthouse

I'll make it okay

When I see your monsters

I'll stand there so brave

And chase them all away

When I see your monsters

I'll stand there so brave

And chase them all away


## 化身孤岛的鲸 {-#hua-shen-gu-dao-de-jing}
 [点击收听](https://y.qq.com/n/ryqq/songDetail/0004adDk3wsULz)
 
***
 
周深

词：沃特艾文儿

曲：徐浩

编曲/制作人：唐汉霄

***

我是只化身孤岛的蓝鲸

有着最巨大的身影

鱼虾在身侧穿行

也有飞鸟在背上停

我路过太多太美的奇景

如同伊甸般的仙境

而大海太平太静

多少故事无人倾听

我爱地中海的天晴

爱西伯利亚的雪景

爱万丈高空的鹰

爱肚皮下的藻荇

我在尽心尽力地多情

直到那一天

你的衣衫破旧

而歌声却温柔

陪我漫无目的的四处漂流

我的背脊如荒丘

而你却微笑摆首

把它当成整个宇宙

你与太阳挥手

也同海鸥问候

陪我爱天爱地的四处风流

只是遗憾你终究

无法躺在我胸口

欣赏夜空最辽阔的不朽

把星子放入眸

我是只化身孤岛的蓝鲸

有着最巨大的身影

鱼虾在身侧穿行

也有飞鸟在背上停

我有着太冷太清的天性

对天上的她动过情

而云朵太远太轻

辗转之后各安天命

我未入过繁华之境

未听过喧嚣的声音

未见过太多生灵

未有过滚烫心情

所以也未觉大洋正中

有多么安静

你的衣衫破旧

而歌声却温柔

陪我漫无目的的四处漂流

我的背脊如荒丘

而你却微笑摆首

把它当成整个宇宙

你与太阳挥手

也同海鸥问候

陪我爱天爱地的四处风流

只是遗憾你终究

无法躺在我胸口

欣赏夜空最辽阔的不朽

把星子放入眸

你的指尖轻柔

抚摸过我所有

风浪冲撞出的丑陋疮口

你眼中有春与秋

胜过我见过爱过

的一切山川与河流

曾以为我肩头

是那么的宽厚

足够撑起海底那座琼楼

而在你到来之后

它显得如此清瘦

我想给你能奔跑的岸头

让你如同王后

## 光亮 {-#guangliang}

[点击收听](https://y.qq.com/n/ryqq/songDetail/001nWLsE4VJqC9)

***

周深

词：苏轼（北宋）/苟璘

曲：钱雷

编曲/制作人：钱雷 

***

海上 一阵风吹起

白云涌向陆地

季风带走沙粒

四季 冷暖的交替

多鲜活的生命

又枯萎的痕迹

是奔跑中突然袭来的风雨

是黑暗中一根火柴燃烧的光明

也许你猜不透未知的宿命

像流星飞翔着它却不知目的

可是啊 我却 却愿意相信

最渺小最微弱最柔软最无畏的你

用尽了全力 努力地回应

再无边再无尽再无解总有一线生机

光亮你自己

戏曲念白：

莫听穿林打叶声

一蓑烟雨任平生

畅音阁里终一叙

六百年一粟 沧海一梦

可是啊 我却 却愿意去相信

最渺小最微弱最柔软最无畏的你

用尽了全力 努力地去回应

再无边再无尽再无解总有一线生机

光亮你自己

戏曲唱腔：

莫听穿林打叶声

一蓑烟雨任平生

畅音阁里终一叙

六百年一粟 沧海一梦

无论目的 最无畏的你

不问宿命 最无畏的你