# 9.29Hz巡回演唱会歌曲歌词 {#appendix-song-lyric}

**Part1**

- [借过一下](#I-will-go-my-way)  
- [Monsters](#Monsters)  
- [化身孤岛的鲸](#hua-shen-gu-dao-de-jing)  
- [光亮](#guangliang)  
- [蓝色降落伞](#lansejiangluosan)
- [若梦](#ruomeng)  
- [浮光](#fuguang)  

**Part2**

- [请我不改](#brave-heart)
- [蜃楼](#mirage)
- [警报](#the-giver)
- [记忆商店](#the-memory-store)
- [嗨](#say-hi)
- [缝合](#fix-you)
- [空壳](#shen)
- [没关系](#life-is-like-a-box-of-chocolates)
- [浅浅](#qianqian)
- [天堂岛之歌](#haven-song)
- [达拉崩吧](#dalabengba)
- [人是_](#renshi)

**Part3**

- [铃芽之旅](#travel-lingya)  
- [触不可及](#untouchable)  
- [欢颜](#happy-face)  
- [My Only](#my-only)  
- [Rubia](#rubia)  
- [小美满](#happy-ending)  
- [好好生活就是美好生活](#live-happy-life-happy)  
- [花开忘忧](#no-worries)  
- [独上西楼](#one-in-the-building)    
- [在水一方](#on-the-water-side)  
- [漫步人生路](#walk-the-road-of-life)  
- [路边的野花不要采](#only-with-me)  
- [我只在乎你](#only-you)  
- [千言万语](#thousands-of-words)  
- [甜蜜蜜](#sweet)  
- [月亮代表我的心](#my-heart-is-moon)  

**Part4**

- [听我说](#listen-to-me)  
- [望](#hope)  
- [北京欢迎你](#welcome-to-beijing)  
- [灯火里的中国](#China-in-the-light)  
- [我在贵州等你](#waitting-in-guizhou)  
- [千年等一回](#once-in-1000)  
- [东北摇篮曲](#lullaby)  
- [奇迹时刻](#magic-moment)  
- [生日祝福歌](#happy-birthday)  
- [wala li longla](#wala-li-longla)  
- [太阳出来喜洋洋](#happy-sun)  
- [山城棒棒军](#nice-chongqing)  
- [璀璨冒险人](#adventurers)  
- [来不及勇敢](#late-to-be-brave)  
- [夏日友晴天](#sunny-day-in-summer)  
- [可它爱着这个世界](#love-the-world)  
- [时结](#shijie)  
- [请笃信一个梦](#believe-your-dream)  
- [微光海洋](#sea-of-shimmer)  
- [三餐四季](#three-meals-a-day)  
- [海藏](#ocean-treasure)  
- [跳舞的月光](#dancing-moonshine)  
- [随风](#with-wind)  
- [一缕执念](#a-wisp-of-obsession)  
- [拙慕](#inferior-admiration)  
- [贝加尔湖畔](#lake-baikal)  
- [春雪](#spring-snow)  
- [孤独的牧羊人](#lonely-shepherd)  
- [漂洋过海来看你](#across-the-ocean-to-see-you)  
- [如愿](#achieve-wishes)  
- [和光同尘](#stay-with-light)  
- [只字不提](#nothing-to-say)  
- [不想睡](#keep-playing)  
- [我以渺小爱你](#love-you)  

**Part5**

- [起风了](#the-wind-rises)
- [大鱼](#big-fish)
- [少管我](#watch-ur-manners)
- [重启](#restart)

## 借过一下 {-#I-will-go-my-way}
[点击收听](https://y.qq.com/n/ryqq/songDetail/00446BOH0yUBXf)

***

周深

词：唐恬

曲：周以力

制作人/编曲：周以力

***

少年扬起脸庞 前往他的月亮

人们笑他狂妄 人怎可不一样

白衣过泥潭 怎敢说不染

但凡银两有价 谁能真潇洒

少年爬上城墙 去见他的月亮

破碎几次心脏 得来几句真相

市井或朝堂 四方皆如框

若你生来有刺 磨掉再入场

你们都是对的他说拜托

让开一下

让我大醉一场 殿堂之上

背闲诗两三章

让我穿白衣裳 过疯人巷

去泥潭捞月光

望大人们见谅 提点的话

我懂也不想装

世人寻黄金乡 我找月亮

何必同往

话谢过 路借过 你是你 我是我

话谢过 路借过 你是你 我是我

诚如先生所说 每颗心都有瑕

潇洒不是不怕 是愿付出代价

权衡利弊后 仍守对与错

谢过赐教的话 路借过一下

让我大醉一场 殿堂之上

背闲诗两三章

让我穿白衣裳 过疯人巷

去泥潭捞月光

望大人们见谅 提点的话

我懂也不想装

世人寻黄金乡 我找月亮

何必同往

话谢过 路借过 你是你 我是我

话谢过 路借过 你是你 我是我

白衣过泥潭 世故里浪漫

知心有所爱 不更改

人见过明暗 若天真犹在

当披上月光 走夜晚

## Monsters {-#Monsters}
[点击收听](https://y.qq.com/n/ryqq/songDetail/004IQQao12ptH0)

***

周深

词：Catherine Beatrice Cheadle/Mads Vathne Lervik/Bjarte Ludvigsen

曲：Catherine Beatrice Cheadle/Mads Vathne Lervik/Bjarte Ludvigsen

***

I see your monsters

I see your pain

Tell me your problems

I'll chase them away

I'll be your lighthouse

I'll make it okay

When I see your monsters

I'll stand there so brave

And chase them all away

In the dark we we

We stand apart we we

Never see that the things we need are staring right at us

You just want to hide hide hide

Never show your smile smile

Stand alone when you need someone

It's the hardest thing of all

That you see are the bad bad bad memories

Take your time you'll find me

I see your monsters

I see your pain

Tell me your problems

I'll chase them away

I'll be your lighthouse

I'll make it okay

When I see your monsters

I'll stand there so brave

And chase them all away

I can see the sky

Beautiful tonight

When you breathe why can't you see

The clouds are in your head

I would stay there

No need to fear

When you need to talk it out with someone you can trust

What you see are the bad bad bad memories

Take your time you'll find me

I see your monsters

I see your pain

Tell me your problems

I'll chase them away

I'll be your lighthouse

I'll make it okay

When I see your monsters

I'll stand there so brave

And chase them all away

You've got the chance to see the light

Even in the darkest night

And I will be here like you were for me

So just let me in

I see your monsters

I see your pain

Tell me your problems

I'll chase them away

I see your monsters

I see your pain

Tell me your problems

I'll chase them away

I'll be your lighthouse

I'll make it okay

When I see your monsters

I'll stand there so brave

I see your monsters

I see your pain

Tell me your problems

I'll chase them away

I'll be your lighthouse

I'll make it okay

When I see your monsters

I'll stand there so brave

And chase them all away

When I see your monsters

I'll stand there so brave

And chase them all away


## 化身孤岛的鲸 {-#hua-shen-gu-dao-de-jing}
 [点击收听](https://y.qq.com/n/ryqq/songDetail/0004adDk3wsULz)
 
***
 
周深

词：沃特艾文儿

曲：徐浩

编曲/制作人：唐汉霄

***

我是只化身孤岛的蓝鲸

有着最巨大的身影

鱼虾在身侧穿行

也有飞鸟在背上停

我路过太多太美的奇景

如同伊甸般的仙境

而大海太平太静

多少故事无人倾听

我爱地中海的天晴

爱西伯利亚的雪景

爱万丈高空的鹰

爱肚皮下的藻荇

我在尽心尽力地多情

直到那一天

你的衣衫破旧

而歌声却温柔

陪我漫无目的的四处漂流

我的背脊如荒丘

而你却微笑摆首

把它当成整个宇宙

你与太阳挥手

也同海鸥问候

陪我爱天爱地的四处风流

只是遗憾你终究

无法躺在我胸口

欣赏夜空最辽阔的不朽

把星子放入眸

我是只化身孤岛的蓝鲸

有着最巨大的身影

鱼虾在身侧穿行

也有飞鸟在背上停

我有着太冷太清的天性

对天上的她动过情

而云朵太远太轻

辗转之后各安天命

我未入过繁华之境

未听过喧嚣的声音

未见过太多生灵

未有过滚烫心情

所以也未觉大洋正中

有多么安静

你的衣衫破旧

而歌声却温柔

陪我漫无目的的四处漂流

我的背脊如荒丘

而你却微笑摆首

把它当成整个宇宙

你与太阳挥手

也同海鸥问候

陪我爱天爱地的四处风流

只是遗憾你终究

无法躺在我胸口

欣赏夜空最辽阔的不朽

把星子放入眸

你的指尖轻柔

抚摸过我所有

风浪冲撞出的丑陋疮口

你眼中有春与秋

胜过我见过爱过

的一切山川与河流

曾以为我肩头

是那么的宽厚

足够撑起海底那座琼楼

而在你到来之后

它显得如此清瘦

我想给你能奔跑的岸头

让你如同王后

## 光亮 {-#guangliang}

[点击收听](https://y.qq.com/n/ryqq/songDetail/001nWLsE4VJqC9)

***

周深

词：苏轼（北宋）/苟璘

曲：钱雷

编曲/制作人：钱雷 

***

海上 一阵风吹起

白云涌向陆地

季风带走沙粒

四季 冷暖的交替

多鲜活的生命

又枯萎的痕迹

是奔跑中突然袭来的风雨

是黑暗中一根火柴燃烧的光明

也许你猜不透未知的宿命

像流星飞翔着它却不知目的

可是啊 我却 却愿意相信

最渺小最微弱最柔软最无畏的你

用尽了全力 努力地回应

再无边再无尽再无解总有一线生机

光亮你自己

戏曲念白：

莫听穿林打叶声

一蓑烟雨任平生

畅音阁里终一叙

六百年一粟 沧海一梦

可是啊 我却 却愿意去相信

最渺小最微弱最柔软最无畏的你

用尽了全力 努力地去回应

再无边再无尽再无解总有一线生机

光亮你自己

戏曲唱腔：

莫听穿林打叶声

一蓑烟雨任平生

畅音阁里终一叙

六百年一粟 沧海一梦

无论目的 最无畏的你

不问宿命 最无畏的你


## 蓝色降落伞 {- #lansejiangluosan}
[点击收听](https://y.qq.com/n/ryqq/songDetail/002foZYi1U2bQP)

***
周深

词：高晓松/尹约

曲：高晓松

编曲：张筱真

制作人：尹约

***

打开窗穿过走廊

下起雨来的弄堂

风里飘散的头发

门里空荡荡的家

我枕头下的梦想

我书包里的惆怅

她们等着我发芽

等到一地的落花

我蓝色的降落伞

在天空里那么孤单

飘向翻涌的人海

望着我被掩埋

那个青涩的男孩

在岁月里那么孤单

蓦然跳下老秋千

忽明忽暗地走远

打开窗穿过走廊

下起雨来的心房

风里飘散的头发

门外空荡荡的家

从不开始的冬天

从未晴朗的屋檐

没人教会我想念

烧成灰烬的木棉

我蓝色的降落伞

在天空里那么孤单

飘向翻涌的人海

望着我被掩埋

那个青涩的男孩

在岁月里那么孤单

他嘴角的那根烟

忽明忽暗地走远

蓝色的降落伞

在天空里那么孤单

飘向翻涌的人海

望着我被掩埋

那个青涩的男孩

在岁月里那么孤单

他嘴角的那根烟

忽明忽暗地走远

## 若梦 {-#ruomeng}
[点击收听](https://y.qq.com/n/ryqq/songDetail/002Id4Xd0F98go)

***
周深  

词：王明毓  

曲：和汇慧/王梓同  

编曲：王子操 (马来西亚)

***

浮生若梦 为欢几何

风摇雨落 此心何处停泊

剑起刀割 却斩不断这因果

看天地之间皆漠漠

尘缘萧索 宿命奈何

日升月落 此生依旧难舍

铁马金戈 也踏不碎这心火

忆前尘旧梦 任岁月 消磨

往事流转在你眼眸

一边遗忘 一边拼凑

如我虔诚合十双手

唯愿你能得到拯救

情缘若梦 长久几何

一枕寒宵 饮下苦涩独酌

杯酒当歌 却绕不开这心锁

愿清欢入梦 伴此心 停泊

往事流转在你眼眸

一边遗忘 一边拼凑

如我虔诚合十双手

唯愿你能得到拯救

往事流转在你眼眸

一边遗忘 一边拼凑

如我虔诚合十双手

唯愿你能得到拯救

唯愿你能得到拯救

## 浮光 {- #fuguang}

[点击收听](https://music.163.com/#/song?id=2112196350)

***
周深

作词 : 唐思淼/邹念慈

作曲 : Jannik

编曲：曾吴秋杰

原编曲：Jannik

***

看指尖拨响蝴蝶 扇动一场离别

我推开无声岁月 续梦一页

你我只是打个照面 可曾有过誓约

走进熟悉却 陌生的思念

啊……

啊……

你的眼眸装满了时间

你的身后拥故事成篇

此生如梦愿细数流年

与你同写 沧海桑田

浮光掠影重山彩云间

你的伏线穿越千百年

人生不过恍惚三万天

漫漫人间 留恋流连

你说那月光 照过同样城墙

永恒的刹那的 此刻沉默无话

想问你这星空 是否不曾变

是啊 是啊

我们望着它

风吹过耳旁 古远的歌唱啊

这是我也是你 不曾遗忘的啊

是来路是去处 是你在回答

去吧 去啊

总会相遇吧

你的眼眸装满了时间

你的身后拥故事成篇

此生如梦愿细数流年

与你同写 沧海桑田

浮光掠影重山彩云间

你的伏线穿越千百年

人生不过恍惚三万天

漫漫人间 留恋流连

## 请我不改 {- #brave-heart}
[点击收听](https://y.qq.com/n/ryqq/songDetail/002qdxkv42Tpzb)

***
周深

词：尹约

曲：钱雷

编曲：钱雷

制作人：钱雷

***

是谁在我 耳边念白

说我不配 我不够好 我必失败

是谁将我 双眼遮盖

惩罚我坠入百无一用的黑暗

是谁不断 日夜合围 向我追来

痛击我最脆弱短板

是谁模糊 我的未来

恐惧淹没了期待

绝望已经大军压境

回身却没半个人影

才看清追兵与逃兵

竟都是我自己

请我不改 我的姿态

我的爱我的痛都与生俱来

请我看开 我的存在

我的明我的暗都不必躲开

我原谅我自己 捡起遗憾拥抱无奈

我允许我放手 让我勇敢活在现在

我不等待 我不徘徊

我的笑我的泪都不再苍白 放肆盛开

(Brave heart)

(Brave heart)

(Brave heart)

是谁不断 日夜合围 向我追来

痛击我最脆弱短板

是谁模糊 我的未来

恐惧淹没了期待

绝望已经大军压境

回身却没半个人影

才看清追兵与逃兵

竟都是我自己

请我不改 我的姿态

我的爱我的痛都与生俱来

请我看开 我的存在

我的明我的暗都不必躲开

我原谅我自己 捡起遗憾拥抱无奈

我允许我放手 让我勇敢活在现在

我不等待 我不徘徊

我的笑我的泪都不再苍白 放肆盛开

(Brave heart)

(Brave heart)

(Brave heart)

暗无天日辗转痛楚

蚌壳终于吐出明珠

微弱光点汇成光束

我向日出更近一步

请我不改 我的姿态

我的爱我的痛都与生俱来

请我看开 我的存在

我的明我的暗都不必躲开

我原谅我自己 捡起遗憾拥抱无奈

我允许我放手 让我勇敢活在现在

我不等待 我不徘徊

我的笑我的泪都不再苍白 坦荡痛快

## 蜃楼 {- #mirage}
[点击收听](https://y.qq.com/n/ryqq/songDetail/00103MrP45XbHm)

***
周深

词：沃特艾文儿

曲：Paula Winger/Austin Heller/Jake Neumar

编曲：Paula Winger/Austin Heller/Jake Neumar

制作人：钱雷

***

看机械的白鸽 从空中飞过

要如何点睛 它才堪称鲜活

数字的晨昏 是否更缤纷

仿生的情人 是否更忠贞

推开一扇门 还有万千重门

生命何尝不是 从乌有 到乌有

倘若感动时候 依然有 泪在流

不管是否身处那蜃楼 世界如何虚构

情愿一生如梦游

（Mirage）

在电幻的荒丘 寻真实的绿洲

渺小得如蜉蝣 也仰望着宇宙

那来自过去 古老的眼神

如何能辨认 此刻是幻是真

人造的天分 是否算慧根

克隆的肉身 是否有灵魂

永远在追问 却从来都没结论

Can it be real

生命何尝不是 从乌有 到乌有

倘若感动时候 依然有 泪在流

不管是否身处那蜃楼 世界如何虚构

情愿一生如梦游

（Mirage）

在电幻的荒丘 寻真实的绿洲

渺小得如蜉蝣 也仰望着宇宙

Can it be real

Can it be real

The world is a mirage

那智慧的天梯 从来都 没尽头

这刹那的感受 却足够 算不朽

我们终身住在那蜃楼 怀中一无所有

仍愿一生如梦游

## 警报 {- #the-giver}
[点击收听](https://y.qq.com/n/ryqq/songDetail/001Ms67n2CZw1q)

***
周深

词：尹约

曲：钱雷

编曲：钱雷

制作人：钱雷

***

迁就对方的节奏

感受对方的感受

请求对方的请求

成就对方的成就

原地不动 不忍失守

你等在情绪代谢的最下游

予取予求 照单全收

别人的任性汹涌

为何你心情表情从来不相通

为何你伤得越重笑得越轻松

不停点头 不折不扣

一付出就是全部的最上游

毫无保留 倾你所有

竟还担心不够

我发送 警报声 血红色 惊叹号

提醒你自救

被遥控 被耗空 快失控 快断送

我替你看透

从借用 到利用 到享用 到滥用

转身就走

他们绝不 为你而痛

共情是一种劳动

温柔是一种苦衷

善良是一种沉重

原谅是一种纵容

人前人后 思前想后

你被困进人情世故的中游

为难左右 无力追究

你终将何去何从

为何你心情表情从来不相通

为何你内心越痛笑得越隆重

千疮百孔 暗藏担忧

你却看不见自己快要断流

回应落空 希望尘封

求救无人听懂

我不断 再计算 因为你 不计算

还能撑多久

给世界 最宽容 给自己 最苛求

顺位排最后

你心口 从伤口 到决口 不开口

笑容始终

我学会痛 为你而痛

## 记忆商店 {- #the-memory-store}
[点击收听](https://y.qq.com/n/ryqq/songDetail/0047wVWr3JcjfC)

***
周深

词：唐恬

曲：Paula Winger/Cash Callaway/Sarah Haglund

编曲：Paula Winger/Cash Callaway/Sarah Haglund

制作人：钱雷

***

有客人从 夜里来

买很古老 的年代

记忆的 货品单

这一款 早售完

不虚拟的拥吻 想不想买

没噩梦的睡眠 耳边goodnight

找遍了 记忆商店

他说想 再荡个秋千

妈妈我想飞得高点

星球以 光速穿越

妈妈我 想落到地面

荡啊荡啊荡个秋千

摇啊晃啊去找花园

买鲸鱼歌声呜咽

岛屿还未消失 这个世界还曾 下着雪

亲爱的 我很抱歉

不朽的 没有了 没人记得

有新款流星雨 人群狂欢

有温暖的炉火 不需要下载 的陪伴

找遍了 记忆商店

他说想 再荡个秋千

妈妈我想飞得高点

星球以 光速穿越

妈妈我 想落到地面

荡啊荡啊荡个秋千

摇啊晃啊去找花园

要找我的秋千

只需要 荡起脚尖

只需要 等着落地

没什么 要明白 没什么 要勇敢

荡啊荡啊荡个秋千

## 嗨 {- #say-hi}
[点击收听](https://y.qq.com/n/ryqq/songDetail/0026jsBv3wjX75)

***

周深

词：金灿灿

曲：Lee Jungwoo/Ritz/Cozy

编曲：Lee Jungwoo/Ritz/Cozy

制作人：钱雷

***

哦说声嗨 知道你一定会来

窗帘在摆 风铃在抖落尘埃

哦我的心 是装满汽水的大海

屏着呼吸 再说声嗨

甜蜜就从全世界涌来

我像在与风相爱

怎样转身你都在

眼前每一粒像素都在摇摆

融化成一片花海

让我一片片碎开

随花瓣轻轻拥向你

你会抱紧我还是摘片云彩

托起我所有盛开

哦说声嗨 太阳边月亮升起来

我唱着歌 小猫尾巴在打节拍

你的身影 喜欢梦中不请自来

不清不白

却总是在 我开始脸红了才离开

我像在与风相爱

怎样转身你都在

眼前每一粒像素都在摇摆

融化成一片花海

让我一片片碎开

随花瓣轻轻拥向你

你会抱紧我还是摘片云彩

托起我所有盛开

哦 是你啊

此刻全宇宙摇摆

随着我心跳开怀

云朵做飞船成排 天空结彩

看我随着风而来

我终于真实存在

终于对自己够坦白

不用为未来 独自犹豫徘徊

紧握的手不松开

嗨 是你啊 

## 缝合 {- #fix-you}
[点击收听](https://y.qq.com/n/ryqq/songDetail/0042wBEj27D3zK)

***
周深

词：周深/王茜

曲：宋阳

编曲：宋阳/钱雷

制作人：钱雷

***

情绪伤口 修补能手

短暂缝合之后又渗出血流

同父母说 相同困惑

也正在大人身体里经历着

不停思索 寻找缘由

听见左胸传来回声的空洞

这不够好 那要改过

无尽的盼头

I'm giving my all

寻找缺口 修补伤口

I'm giving my all

缝补之后 又再次泪流

I'm giving my all

新的伤痕 旧的内疚

I'm giving my all

如何才能 找到出口

否定成果 爽约承诺

都缝合成细腻温柔的眼色

落单门口 独行角落

都包扎成坚强独立的成就

重复工作 重复失落

调换角色修补找新的成果

不同身体 不同角落

同样的苦痛

I'm giving my all

大人背后 常乌云盖着

I'm giving my all

孩子内心 底色是晴的

I'm giving my all

白的天空 留了一滴墨

I'm giving my all

如何调色 如何来涂抹

所有无助的绑住的困住的

我都清楚却也无法挣脱

所有偏执的逃离的期盼的

他们都懂也无法从头来过

I'm giving my all

各自运转 各自角色

I'm giving my all

你们都是 第一次活着

I'm giving my all

万般无意 伤口却留着

I'm giving my all

伤痕再多 也值得被爱着

## 空壳 {- #shen}
[点击收听](https://y.qq.com/n/ryqq/songDetail/003KAMkE38B4i6)

***
周深

词：周深

曲：钱雷

编曲：钱雷

制作人：钱雷

***

他们都说我只是个空壳

不懂残酷或温柔的面孔

而你却从远方走来 带着信物

一点点把我 填满了

有你爱的存钱筒

有你赢的小弹球

有你收的第一束花

有你等好久好久把第一双鞋拥有

有你看了又看终于带离橱窗的裙

你说这都叫做甜的

还有不愿放的手

被生活压低的头

有你总一个人在漆黑隧道里走

有送不到的问候

有无人听懂的痛

都一一交付于我

原来这叫苦的

我带着它们走

全都视为珍重

在与你告别后

才明白这叫做拥有

懂得了滋味的空壳

不懂为何信任那么多 却给了我

长出了血肉的空壳

开始感觉比从前更空 是你给的

没装满的存钱筒

落满灰尘的弹球

第一束花也已凋落

那终将放开的手

那无力抬起的头

你全给我毫无保留

我欣然都接受

空和满在此刻换手

而你却还在问我

填满空壳的意义

可我只是害怕你

弄丢了你自己

你说旧的你已经

就快要分崩离析

还不知道新的你

该在哪里找寻

我带着它们去

也许再次相遇

再轻轻拥抱你

这空壳是我 也是你

也是你

## 没关系 {-#life-is-like-a-box-of-chocolates}
[点击收听](https://y.qq.com/n/ryqq/songDetail/001EGnjy1qhO94)

***
周深

词：金灿灿

曲：钱雷

编曲：钱雷

制作人：钱雷

***

世界其实很有趣 像解题

简单的问题总是 更犹豫

为难了自己

哭吗 感动但是委屈

笑吗 快乐或算了

吃吗 清晨和夜里

睡吗 整颗心翻来覆去

其实都没有关系

我们都是泥 (掺一点杂质也可以)

压缩着呼吸 (等变形的美丽)

被踩在脚底 (这双鞋有缝隙)

回答不出的问题 说不清的道理

其实都没有关系

那些丢开的玩具 在哪里

那藏起来的叹气 和秘密

被留在心底

哭吧 只是下一场雨

笑吧 呵呵或嘻嘻

吃吧 让甜蜜具体

睡吧 让夜晚抹去意义

其实都没有关系

我们会呼吸 (已是空气给的奖励)

我们在努力 (向着风景迁徙)

我们会犹豫 (停下看得清晰)

一路不停在解题 以身填补着缝隙

同时拼凑了自己

哭啊 哭啊

找啊 找啊

找不到也没关系


## 浅浅 {- #qianqian}
[点击收听](https://y.qq.com/n/ryqq/songDetail/0003aeAg2mVhJN)

***
周深

词：尹约

曲：钱雷

编曲：钱雷

制作人：尹约

***
 
子夜 浅浅的戒痕浅浅的长街

残月 浅浅的亲吻深深的离别

你看 孤独穿着黑袍安静站在门口

可惜 连她都不愿向我抬起手

叶 深深去回忆又深深凋谢

望 穿一树枯黄

心 心中琴房

不知趣怦怦地弹出你的模样

子夜 浅浅的戒痕浅浅的长街

残月 浅浅的亲吻深深的离别

你看 孤独穿着黑袍安静站在门口

可惜 连她都不愿向我抬起手

叶 深深去回忆又深深凋谢

望 穿一树枯黄

心 心中琴房

不知趣怦怦地弹出你的模样

## 天堂岛之歌 {- #haven-song}
[点击收听](https://y.qq.com/n/ryqq/albumDetail/000GJWeQ1Sx0Is)

***
周深

***

叮咚 我有一个秘密

悄悄告诉你

欢迎你来到天堂入口

叮咚 有人在按门铃

是谁在外面

把恶作剧当一种游戏

听啊谁在哭泣

看啊谁在窃窃私语

窗外有双眼睛

它在时刻注视着你

叮咚 我在这里等你

你在等我吗

是什么原因让你害怕

叮咚 你会藏在哪里

别想要逃离

想逃出手心已来不及

被遗忘的记忆

被你藏起来的秘密

不要大声呼吸

你已暴露了你自己

Knock knock 外面下起了雨

放弃挣扎吧

谎言说多了就会发现

Knock knock 是谁在做坏事

假装成幸运

我总会找到你在床底

听啊 你在恐惧

看啊 你在歇斯底里

窗外有双眼睛

它在时刻注视着你

## 达拉崩吧 {- #dalabengba}
[点击收听](https://y.qq.com/n/ryqq/songDetail/002kN8FY1hPhAC)

***
周深

词：ilem

曲：ilem

编曲：孔潇一

原唱：洛天依/言和

Program：孔潇一

制作人：孔潇一

***

小女孩：

很久很久以前 巨龙突然出现

带来灾难 带走了公主又消失不见

王国十分危险 世间谁最勇敢

一位勇者赶来 大声喊

少年：

我要带上最好的剑 翻过最高的山

闯进最深的森林 把公主带回到面前

小女孩：

国王非常高兴 忙问他的姓名

年轻人想了想 他说

陛下我叫

达拉崩吧斑得贝迪卜多比鲁翁

国王：

再说一次

少年：

达拉崩巴斑得贝迪卜多比鲁翁

国王：

是不是

达拉崩吧斑得贝迪卜多比鲁翁

少年：

对对 达拉崩巴斑得贝迪卜多比鲁翁

旁白：

英雄达拉崩吧 骑上最快的马

带着大家的希望从城堡里出发

战胜怪兽来袭 获得十二金币

无数伤痕见证 他慢慢升级

小女孩：

偏远美丽村庄 打开所有宝箱

一路风霜伴随指引前路的圣月光

闯入一座山洞 公主和可怕的巨龙

英雄拔出宝剑 巨龙说

巨龙：

我是 昆图库塔卡提考特苏瓦西拉松

少年：

再来一次

巨龙：

昆图库塔卡提考特苏瓦西拉松

少年：

是不是 昆特牌提琴

烤蛋挞 苏打 马拉松

巨龙：

不对

是昆图库塔卡提考特苏瓦西拉松

旁白：

于是

少年：

达拉崩巴斑得贝迪卜多比鲁翁

旁白：

砍向

巨龙：

昆图库塔卡提考特苏瓦西拉松

旁白：

然后

巨龙：

昆图库塔卡提考特苏瓦西拉松

旁白：

咬了

少年：

达拉崩吧斑得贝迪卜多比鲁翁

旁白：

最后

达拉崩巴斑得贝迪卜多比鲁翁

他战胜了

巨龙：

昆图库塔卡提考特苏瓦西拉松

旁白：

救出了

公主米娅莫拉苏娜丹妮谢莉红

回到了

蒙达鲁克硫斯伯古比奇巴勒城

国王听说

达拉崩巴斑得贝迪卜多比鲁翁

他打败了

昆图库塔卡提考特苏瓦西拉松

就把 公主米娅莫拉苏娜丹妮谢莉红

嫁给

达拉崩吧斑得贝迪卜多比鲁翁

啦啦 达拉崩巴 公主米娅

幸福得像个童话

他们生下一个孩子

也在天天渐渐长大

为了避免以后麻烦 孩子称作王浩然

他的全名十分难念 要念你来念吧

## 人是_ {- #renshi}
[点击收听](https://y.qq.com/n/ryqq/songDetail/001zuNRq15kB7v)

***
周深

词：唐恬

曲：钱雷

编曲：钱雷

制作人：钱雷

***

去往 所有 命运 风暴之中的盲童

你来自火山炙热 与苦寒的深海

生本 就是 意外 硬币反选为尘埃

为侥幸可以相爱 造了船 移着山

出征是古老的宿命

人将赤足踏入夜晚

只有我可以来决定 我以何种姿态

让死亡觊觎我

让恐惧亲吻我

来摧毁我深爱的一切

可仍夺不走我的选择

弹指间湮灭我

但命运打不败活着

让生命如剧烈的烟火

璀璨熄灭前也将点亮

孩童的双眸

未知 摊开 棋局 舍弃昨日才可破

再见了我的月光 我的蓝 我的爱

钢铁的巨兽在轰鸣 我们拒绝走入夜晚

破碎是新生的约定 我便愿为尘埃

让死亡觊觎我

让恐惧亲吻我

来摧毁我深爱的一切

可仍夺不走我的选择

弹指间湮灭我

但命运打不败活着

让生命如剧烈的烟火

璀璨熄灭前也将点亮

孩童的双眸

若巨浪已淹没了来路 我是帆 亦是舟

是微渺 的希望

我们依然前行 没有光指引

往前吧 失去吧 不要停留

让时空消亡我

你无需记得我

来摧毁我深爱的一切

可仍夺不走我的选择

弹指间湮灭我

但命运打不败活着

是微茫中高歌的族类

生命像烟火那就点亮

孩童的双眸

未来的瞳孔


## 铃芽之旅 {- #travel-lingya}
[点击收听](https://y.qq.com/n/ryqq/songDetail/001DOs0n2E7ttc)

***
周深

词：野田洋次郎

中文词：白夜/午上/袁天野

曲：野田洋次郎

编曲：RADWIMPS

***

哼唱

于 你的生命之中

红与蓝的线缠绕交错

在 心间划上最后一笔

勾勒出你的脉络

那 随风飘荡的声音

从不曾被吹散片刻

是 藏在心中的话想对你说

却还没能说

人生啊 短暂如花

微风啊 拂过脸颊

星光啊 照谁的家

我们是 宇宙一刹

别再问 别再问 这样的我 为什么哭着

眼泪替我诉说

意义是你 意义是我

意义总是 难以追寻的

是我们相遇过 谁奋力呐喊着

却吼不破命运的壳

只能是你 只能由你

触碰双手 轻轻唤醒我

沉睡千年的心搏

意义是你 意义是我

意义是否 最终跨越呢

相隔时空的你我

是愚昧又如何 是丑恶又如何

是望着前方 正确的因果

是想与你携手走过

如今我已想不起

曾经珍惜的回忆

却似有万千言语

深深埋葬在我心底

或许就这样吧 或许就这样了

还有什么遗憾的

我已交付所有的自己

或许就这样吧 或许就这样了

多么想让你听见

这颗破碎又顽强的心

只想靠近你

别再问 别再问 这样的我 为什么哭着

眼泪替我诉说

意义是你 意义是我

意义总是 难以追寻的

是我们相遇过 谁奋力呐喊着

却吼不破命运的壳

只能是你 只能由你

触碰双手 轻轻唤醒我

沉睡千年的心搏

意义是你 意义是我

意义是否 最终跨越呢

相隔时空的你我

是愚昧又如何 是丑恶又如何

是望着前方 正确的因果

是想与你携手走过


## 触不可及 {- #untouchable}
[点击收听](https://y.qq.com/n/ryqq/songDetail/002EFRnf3ekI9S)

***
周深

词：祁辛

曲：崔克檐

编曲：边疆

制作人：祁辛

***

触不可及 又何必在意

Life will be easier when the sunlight in

触不可及 未来的自己

To keep on pushing on down the lonely street

Down the lonely street

无数个心灰意冷的夜里

梦见我在半空飞行

漫无目的

有时候我靠在窗前看着

街上行人冷漠表情

匆匆的来去

不止一次我想要放弃 不再执迷

却陷入患得患失的漩涡里

触不可及 又何必在意

Life will be easier when the sunlight in

触不可及 未来的自己

To keep on pushing on down the lonely street

Down the lonely street

当夜幕将临我要开车出去

驶向远方油门到底

去哪儿 没关系

再放一首我最爱的音乐

跟着节奏摇摆身体

舞步就随意

现实总是太过强硬 太多难题

我只想去看沿途最美的风景

触不可及 又何必在意

Life will be easier when the sunlight in

触不可及 未来的自己

To keep on pushing on down the lonely street

触不可及 又何必在意

Life will be easier when the sunlight in

触不可及 未来的自己

To keep on pushing on down the lonely street

Down the lonely street

Down the lonely street

Down the lonely street

## 欢颜 {- #happy-face}
[点击收听](https://y.qq.com/n/ryqq/songDetail/001TW8Rg3ZXH5N)

***
周深

词：沈吕百

曲：李泰祥

***

飘落着淡淡愁

一丝丝的回忆

如梦如幻如真

弦轻拨声低吟

那是歌

只要你轻轻一笑

我的心就迷醉

只有你的欢颜笑语

伴我在漫漫长途有所依

春雨秋霜岁月无情

海枯石烂形无痕

只有你的欢颜笑语

伴我在漫漫长途有所依

飘落着冷冷清

万缕缕的怀念

如梦如幻如真

弦轻拨声低吟

那是歌啦啦啦

## My Only {- #my-only}
[点击收听](https://y.qq.com/n/ryqq/songDetail/002RU1we0BuhyA)

***
周深

词：王仕琳

曲：金炫道

***

You are the only

The only one who heals me

When I look into your eyes

I heard my heart beat oh oh

Please be my only

The only one who I need

How can I imagine life without you

Never leave me alone

Don't go far away

Just stay with me

You are my only

The only one who found me

In the darkness but only you saw me

Tomorrow just let it be

Cause I know you'll come with me

You are my only

Always believed in me

I will never be that weak-willed me

I'll be strong with you by me

How can I let you go away

You are my only

Always on my mind

But it's so hard to find out why

Dreaming of you every night

I wonder why you never know

You are my only

Always be there waiting for me

I will never leave

I will be right there for you

It seems like the real meaning

To me

## Rubia {- #rubia}
[点击收听](https://y.qq.com/n/ryqq/songDetail/001OPnK236dSE7)

***
周深

词：TetraCalyx

曲：蔡近翰Zoe(HOYO-MiX)

编曲：宫奇Gon(HOYO-MiX)/杨启翔Frex(HOYO-MiX)

***

Life blooms like a flower

Far away or by the road

Waiting for the one

To find the way back home

Rain falls a thousand times

No footprints of come-and-go

You who once went by

Where will you belong

I feel your sigh and breath

In the last blow of wind

Not yet for the story on the last page

It's not the end

Life blooms like a flower

Far away or by the road

Waiting for the one

To find the way back home

Time flows across the world

There is always a longer way to go

Till I reach your arms

A Madder there for you

Up against the stream

Waterways will join as one

Tracing to the source

No more strayed or lost

You will see petals fly

When lament becomes carol

Could you please hear my voice

That hungers for a duo

Life blooms like a flower

Far away or by the road

Waiting for the one

To find the way back home

Time flows across the world

There is always a longer way to go

Till I reach your arms

A Madder there for you

Life blooms like a flower

Far away or by the road

Waiting for the one

To find the way back home

Time flows across the world

There is always a longer way to go

Till I reach your arms

A Madder there for you

## 小美满 {- #happy-ending}
[点击收听](https://y.qq.com/n/ryqq/songDetail/002QvWwX1BG9mr)

***
周深

词：李聪

曲：彭飞

编曲：彭飞

制作人：彭飞

***

没什么 大愿望

没有什么事 要赶

看见路口红灯 一直闪

它像 眨眼的小太阳

乌云还 挺大胆

顶在头上 吹不散

我抓在手里 捏成棉花糖

什么烦恼 不能忘

既然 是路一定有转弯

哪个风景 都漂亮

揉揉疲惫的眼睛 停下来 看一看

美好简单

你看

小狗在叫 树叶会笑

风声在呢喃

不如好好 欣赏一秒

迷迷糊糊的 浪漫

只要 一觉醒来 床单洒满

阳光的 温暖

不去想 不必想

不用急急忙忙 说一个 答案

笑一笑 就灿烂

唱一句歌 就舒展

收集一点一滴 小美满

都是 幸福的花样

没道理 的开朗

打扮 平凡的日常

找到自己 最合身的衣裳

只要自己 够喜欢

至少 还有温柔的眼光

还在夜里 看月亮

心情铺得再满 也要留一扇天窗

岁月很长

你看

小狗在叫 树叶会笑

风声在呢喃

不如好好 欣赏一秒

迷迷糊糊的浪漫

只要 一觉醒来 床单洒满

阳光的温暖

不去想 不必想

不用急急忙忙 说一个 答案

你愿相信什么

就把世界 看成什么样

偶尔难题 加点重量

越要 轻轻地旋转

所以 无论如何

记得保管 小小的光环

笑就好 哭也好

今天 就是明天最好的 陪伴

笑就好 哭也好

自己 就是自己最好的 陪伴


## 好好生活就是美好生活 {- #live-happy-life-happy}
[点击收听](https://y.qq.com/n/ryqq/songDetail/003cDEFF0oQAKb)

***
周深

词：张莹/刘文策

曲：苏靖凯

编曲：茶茶

制作人：茶茶

***

想起我小时候 喜欢在雨中奔跑

想要买张车票 去给她一个拥抱

等铺上了地毯 也要养上一只猫

晚霞染红天空 沉闷日子会有风

曾经害怕的她 现在还牵挂着他

晚风轻抚脸颊 心事也慢慢放下

亲爱的朋友啊 我要拉着你慢跑

想和她有个家 就像梦里的那样

狂风 不停 我也不会畏惧

因为有你 和我一起

人生多么美妙 记得保持微笑

美好生活都将你拥抱

好好得吃个饭 好好得睡一觉

好好生活 原来就是美好

唱一首我怀念的 遇见青春年少

这平凡的一天 庆祝没虚度一秒

夺冠的一瞬间 眼里含满了骄傲

神舟飞向了太空 仰望天宫英雄

人生多么美妙 记得保持微笑

美好生活都将你拥抱

好好得吃个饭 好好得睡一觉

好好生活 原来就是美好

在夕阳下奔跑 日子扬起微笑

美好生活尽情地舞蹈

好好经历长大 好好陪你变老

好好地记录 好好的美好

新的一年 我们一定要好好

新的一天 我们一定好好

## 花开忘忧 {- #no-worries}
[点击收听](https://y.qq.com/n/ryqq/songDetail/004czGF42WSgko)

***
周深

词：唐恬

曲：钱雷

编曲：钱雷

制作人：钱雷

***

巷子口 买了花

穿过沿街红墙青瓦

夕阳慢慢亲吻着 我的白发

推开旧木门 回到家

把时光 都炖香

而你只是笑 不说话

一件遗憾的事 就喝一碗汤

庭院深深 秋叶飘落

我们苍老的时候 就回到小时候

采青梅用来酿酒你 不许偷着喝

穿朴素的衣裳 牵着那衣袖

捡了小猫 名为苍狗

我们睡去的时候 像孩子无忧愁

反正也很难上锁这 岁月如小偷

若记忆被偷走了 忘了我的爱

我会说 你好啊

这是给 你的花

花的名字叫忘忧草

它说时光汹涌 如水上烟波

别走远了 一起回家

我们苍老的时候 就回到小时候

采青梅用来酿酒你 不许偷着喝

穿朴素的衣裳 牵着那衣袖

捡了小猫 名为苍狗

我们睡去的时候 像孩子无忧愁

在梦里做个梦 看见你我都老了

那永恒没骗我 离散也没有

这份爱只是活在 另外时空

如果 每一声再见 会开启

一个新的空间

每做一个梦 是时空 偶尔的重叠

你好吗 离开的人啊

请帮我 相爱到剧终

忘忧草 开着花

你在月光下 不说话

一件遗憾的事 就喝一杯茶

庭院深深 秋叶飘落

## 独上西楼 {- #one-in-the-building}
[点击收听](https://y.qq.com/n/ryqq/songDetail/0030DkCJ0IhAPO)

***
邓丽君

词：李煜

曲：刘家昌

***

无言独上西楼

月如钩

寂寞梧桐

深院锁清秋

剪不断理还乱

是离愁

别有一番滋味在心头

无言独上西楼

月如钩

寂寞梧桐

深院锁清秋

剪不断理还乱

是离愁

别有一番滋味在心头

剪不断理还乱

是离愁

别有一番滋味在心头

无言独上西楼

月如钩

寂寞梧桐

深院锁清秋

剪不断理还乱

是离愁

别有一番滋味在心头

## 在水一方 {- #on-the-water-side}
[点击收听](https://y.qq.com/n/ryqq/songDetail/001jTorH1knD1B)

***
邓丽君

词：琼瑶

曲：林家庆

***

绿草苍苍

白雾茫茫

有位佳人

在水一方

绿草萋萋

白雾迷离

有位佳人

靠水而居

我愿逆流而上

依偎在她身旁

无奈前有险滩

道路又远又长

我愿顺流而下

找寻她的方向

却见依稀仿佛

她在水的中央

我愿逆流而上

与她轻言细语

无奈前有险滩

道路曲折无已

我愿顺流而下

找寻她的踪迹

却见仿佛依稀

她在水中伫立

绿草苍苍

白雾茫茫

有位佳人

在水一方


## 漫步人生路 {- #walk-the-road-of-life}
[点击收听](https://y.qq.com/n/ryqq/songDetail/000kdYZe2pYypq)

***
邓丽君

词：郑国江

曲：中岛美雪

***

未疲倦

伴你漫行

一段接一段

越过高峰

另一峰却又见

目标推远

让理想永远在前面

路纵崎岖

亦不怕受磨练

愿一生中

苦痛快乐也体验

愉快悲哀

在身边转又转

风中赏雪

雾里赏花

快乐回旋

不用计较

快欣赏身边

美丽每一天

还愿确信

美景良辰在脚边

愿将欢笑声

盖掩苦痛那一面

悲也好 喜也好

每天找到新发现

让疾风吹呀吹

尽管给我俩考验

小雨点 放心洒

早已决心向着前

路纵崎岖

亦不怕受磨练

愿一生中

苦痛快乐也体验

愉快悲哀

在身边转又转

风中赏雪

雾里赏花

快乐回旋

不用计较

快欣赏身边

美丽每一天

还愿确信

美景良辰在脚边

愿将欢笑声

盖掩苦痛那一面

悲也好 喜也好

每天找到新发现

让疾风吹呀吹

尽管给我俩考验

小雨点 放心洒

早已决心向着前


## 路边的野花不要采 {- #only-with-me}
[点击收听](https://y.qq.com/n/ryqq/songDetail/0036Mswl2K9hCm)

***
邓丽君

词：林煌坤

曲：Huang Kun Lin 李俊雄

***

送你送到小村外

有句话儿要交待

虽然已经是百花开

路边的野花你不要采

记着我的情记着我的爱

记着有我天天在等待

我在等着你回来

千万不要把我来忘怀

送你送到小村外

有句话儿要交待

虽然已经是百花开

路边的野花你不要采

记着我的情记着我的爱

记着有我天天在等待

我在等着你回来

千万不要把我来忘怀

千万不要把我来忘怀

千万不要把我来忘怀


## 我只在乎你 {- #only-you}
[点击收听819深深感谢你版](https://y.qq.com/n/ryqq/songDetail/002EX2Ak2wR62v)

***

词：三木たかし/荒木とよひさ/慎芝

曲：三木たかし/荒木とよひさ

***

如果没有遇见你

我将会是在哪里

日子过得怎么样

人生是否要珍惜

也许认识某一人

过着平凡的日子

不知道会不会

也有爱情甜如蜜

任时光匆匆流去

我只在乎你

心甘情愿感染你的气息

人生几何能够得到知己

失去生命的力量也不可惜

所以我求求你

别让我离开你

除了你 我不能感到

一丝丝情意

如果有那么一天

你说即将要离去

我会迷失我自己

走入无边人海里

不要什么诺言

只要天天在一起

我不能只依靠

片片回忆活下去

任时光匆匆流去

我只在乎你

心甘情愿感染你的气息

人生几何能够得到知己

失去生命的力量也不可惜

所以我求求你

别让我离开你

除了你 我不能感到

一丝丝情意

任时光匆匆流去

我只在乎你

心甘情愿感染你的气息

人生几何能够得到知己

失去生命的力量也不可惜

所以我求求你

别让我离开你

除了你 我不能感到

一丝丝情意


## 千言万语 {- #thousands-of-words}
[点击收听](https://y.qq.com/n/ryqq/songDetail/000yyrRd1XgqDZ)

***
词：古月

曲：古月

***

不知道为了什么

忧愁它围绕著我

我每天都在祈祷

快赶走爱的寂寞

那天起 你对我说

永远的爱著我

千言和万语随浮云掠过

不知道为了什么

忧愁它围绕著我

我每天都在祈祷

快赶走爱的寂寞

不知道为了什么

忧愁它围绕著我

我每天都在祈祷

快赶走爱的寂寞

那天起 你对我说

永远的爱著我

千言和万语随浮云掠过

不知道为了什么

忧愁它围绕著我

我每天都在祈祷

快赶走爱的寂寞

## 甜蜜蜜 {- #sweet}
[点击收听](https://y.qq.com/n/ryqq/songDetail/000sdZNg1W94eK)

***
邓丽君 (Teresa Teng)

词：庄奴

曲：Indonesian Folk Song

***

甜蜜蜜

你笑得甜蜜蜜

好像花儿开在春风里

开在春风里

在哪里

在哪里见过你

你的笑容这样熟悉

我一时想不起

啊 在梦里

梦里梦里见过你

甜蜜笑得多甜蜜

是你 是你

梦见的就是你

在哪里

在哪里见过你

你的笑容这样熟悉

我一时想不起

啊 在梦里

在哪里

在哪里见过你

你的笑容这样熟悉

我一时想不起

啊 在梦里

梦里梦里见过你

甜蜜笑得多甜蜜

是你 是你

梦见的就是你

在哪里

在哪里见过你

你的笑容这样熟悉

我一时想不起

啊 在梦里

## 月亮代表我的心 {- #my-heart-is-moon}
[点击收听](https://y.qq.com/n/ryqq/songDetail/003nYgF01aN0yF)

***
邓丽君

词：孙仪

曲：翁清渓

编曲：卢东尼

***

你问我爱你有多深

我爱你有几分

我的情也真

我的爱也真

月亮代表我的心

你问我爱你有多深

我爱你有几分

我的情不移

我的爱不变

月亮代表我的心

轻轻的一个吻

已经打动我的心

深深的一段情

叫我思念到如今

你问我爱你有多深

我爱你有几分

你去想一想

你去看一看

月亮代表我的心

轻轻的一个吻

已经打动我的心

深深的一段情

叫我思念到如今

你问我爱你有多深

我爱你有几分

你去想一想

你去看一看

月亮代表我的心

你去想一想

你去看一看

月亮代表我的心

## 听我说 {- #listen-to-me}
[点击收听](https://music.163.com/#/song?id=1415078941)

***
周深

作词 : 茶茶

作曲 : 茶茶

编曲 : 茶茶

***

已经数不清第几次

这样蹒跚的日子

这些年过的不简单

还有一些未知的难

踏平旅途的孤单

回头看也算平凡

人世间总会有心酸

还好有我们做伴

听我说

可以听我说

我有时懒惰有时脆弱

有时像一个未经世俗的孩子

还不懂复杂与颠簸

不要失落

就这样听我说

若没有曲折怎懂快乐

开心和难过总要找个人说说

日子总会变好的

踏平旅途的孤单

回头看也算平凡

人世间总会有心酸

还好有家是靠岸

听我说

可以听我说

我跨过千山走到灯火

飞快的掠过

春去秋来的颠簸

那不停呼唤的院落

不要失落

就这样听我说

若没有曲折怎懂快乐

开心和难过总要找个人说说

那个人总会懂的

听我说

可以听我说

我跨过千山走到灯火

飞快的掠过

春去秋来的颠簸

那不停呼唤的院落

不要失落

就这样听我说

若没有曲折怎懂快乐

开心和难过总要找个人说说

日子总会变好的

开心和难过总要找个人说说

那个人总会懂的

## 望 {- #hope}
[点击收听](https://music.163.com/#/song?id=1814080666)

***
周深

作词 : 申名利

作曲 : 音融三喜

编曲 : 周富坚/袁文睿

制作人 : 周富坚/袁文睿

***

红色风筝 俯瞰着地图

飘太远 在哪儿 着陆

远行的人 是望远镜里的模糊

借背影放大孤独

你我习惯 像常旅客来了又去

寄天空的信 未能 按时 回复

再等一等就返航 如初

我们总会 绕啊绕 绕啊绕

绕几千里路 也望向归途

乘着风想念吹拂 游夜空漂浮

抓一颗流星做礼物 愿你幸福

手中线 绕啊绕 绕啊绕

绕几千日夜 也望向归途

燕归巢迁徙之路 参与者无数

待到烟火照夜白时准备庆祝 心有所住

儿时总爱 掰着手默数

好希望 快些到 日出

长大的人 被挟裹着说不得不

借不到借口停驻

你我习惯 像常旅客来了又去

寄天空的信 未能 按时 回复

再等一等就返航 如初

我们总会 绕啊绕 绕啊绕

绕几千里路 也望向归途

乘着风想念吹拂 游夜空漂浮

抓一颗流星做礼物 愿你幸福

手中线 绕啊绕 绕啊绕

绕几千日夜 也望向归途

燕归巢迁徙之路 参与者无数

待到烟火照夜白时准备庆祝 心有所住

我们总会 绕啊绕 绕啊绕

绕几千里路 也望向归途

乘着风思念吹拂 游夜空漂浮

抓一颗流星祝福 你要幸福

手中线 绕啊绕 绕啊绕

绕几千日夜 也望向归途

燕归巢迁徙之路 参与者无数

待到烟火照夜白时准备庆祝 心有所住

## 北京欢迎你 {- #welcome-to-beijing}
[点击收听](https://y.qq.com/n/ryqq/songDetail/001V0G0L1vsPDg)

***
词：林夕

曲：小柯

***

迎接另一个晨曦

带来全新空气

气息改变情味不变

茶香飘满情谊

我家大门常打开

开放怀抱等你

拥抱过就有了默契

你会爱上这里

不管远近都是客人

请不用客气

相约好了再一起

我们欢迎你

我家种着万年青

开放每段传奇

为传统的土壤播种

为你留下回忆

陌生熟悉都是客人

请不用拘礼

第几次来没关系

有太多话题

北京欢迎你

为你开天辟地

流动中的魅力充满着朝气

北京欢迎你

在太阳下分享呼吸

在黄土地刷新成绩

我家大门常打开

开怀容纳天地

岁月绽放青春笑容

迎接这个日期

天大地大都是朋友

请不用客气

画意诗情带笑意

只为等待你

北京欢迎你

像音乐感动你

让我们都加油去超越自己

北京欢迎你

有梦想谁都了不起

有勇气就会有奇迹

北京欢迎你

为你开天辟地

流动中的魅力充满着朝气

北京欢迎你

在太阳下分享呼吸

在黄土地刷新成绩

北京欢迎你

像音乐感动你

让我们都加油去超越自己

北京欢迎你

有梦想谁都了不起

有勇气就会有奇迹

北京欢迎你呀

我家大门常打开

开放怀抱等你

拥抱过就有了默契

你会爱上这里

不管远近都是客人

请不用客气

相约好了再一起

我们欢迎你

北京欢迎你

为你开天辟地

流动中的魅力充满着朝气

北京欢迎你

在太阳下分享呼吸

在黄土地刷新成绩

我家大门常打开

开怀容纳天地

岁月绽放青春笑容

迎接这个日期

天大地大都是朋友

请不用客气

画意诗情带笑意

只为等待你

北京欢迎你

像音乐感动你

让我们都加油去超越自己

北京欢迎你

有梦想谁都了不起

有勇气就会有奇迹

北京欢迎你

为你开天辟地

流动中的魅力充满着朝气

北京欢迎你

在太阳下分享呼吸

在黄土地刷新成绩

北京欢迎你

像音乐感动你

让我们都加油去超越自己

北京欢迎你

有梦想谁都了不起

有勇气就会有奇迹

北京欢迎你

有梦想谁都了不起

有勇气就会有奇迹

北京欢迎你

有梦想谁都了不起

有勇气就会有奇迹

## 灯火里的中国 {- #China-in-the-light}
[点击收听](https://y.qq.com/n/ryqq/songDetail/003u1hCW1K49DP)

***
周深

词：田地

曲：舒楠

***

都市的街巷 已灯影婆娑

社区暖暖流淌的欢乐

远山的村落 火苗闪烁

渐渐明亮小康的思索

归港的船帆 从灯塔掠过

追梦脚步月下交错

广场焰火在节日诉说

星空升腾时代的巍峨

灯火里的中国 青春婀娜

灯火里的中国 胸怀辽阔

灯火漫卷的万里山河

初心换回了百年承诺

灯火里的中国 青春婀娜

灯火里的中国 胸怀辽阔

灯火灿烂的中国梦

灯火荡漾着心中的歌

归港的船帆 从灯塔掠过

追梦脚步月下交错

广场焰火在节日诉说

星空升腾时代的巍峨

灯火里的中国 青春婀娜

灯火里的中国 胸怀辽阔

灯火灿烂的中国梦

灯火荡漾着心中的歌

灯火里的中国 青春婀娜

灯火里的中国 胸怀辽阔

灯火漫卷的万里山河

初心换回了百年承诺

灯火里的中国 青春婀娜

灯火里的中国 胸怀辽阔

灯火灿烂的中国梦

灯火荡漾着心中的歌

灯火荡漾着心中的歌

## 我在贵州等你 {- #waitting-in-guizhou}
[点击收听](https://y.qq.com/n/ryqq/songDetail/001E9vLv3FYvmQ)

***
周深

词：玉镯儿

曲：张超

***

等到天都蓝了 等到云都白了

等到每缕微风 都带着醉意

等到花都开了 等到山顶红了

等到每颗星星 都为你亮起

我在贵州等你 等你和我相遇

等待如此美丽 嘿久

等到天都蓝了 等到云都白了

等到每缕微风 都带着醉意

等到花都开了 等到山顶红了

等到每颗星星 都为你亮起

我在贵州等你 等你和我相遇

等待如此美丽

嘿久

等到花都开了 等到山顶红了

等到每颗星星 都为你亮起

我在贵州等你 等你和我相遇

等待如此美丽 嘿久

## 千年等一回 {- #once-in-1000}
[点击收听](https://y.qq.com/n/ryqq/songDetail/001J1JRi4f2Nj0)

***
周深

词：陈自为

曲：古月

***

千年等一回

等一回啊

千年等一回

我无悔啊

千年等一回

等一回啊

千年等一回

我无悔啊

是谁在耳边说

爱我永不变

只为这一句

啊哈断肠也无怨

雨心碎风流泪哎

梦缠绵情悠远嘞

Chi China

Chi China

Chi China

Chi China

西湖的水我的泪

我情愿和你化做一团火焰

啊啊啊

千年等一回

等一回啊

千年等一回

我无悔啊

雨心碎风流泪哎

梦缠绵情悠远哎

Chi China

Chi China

Chi China

Chi China

西湖的水我的泪

我情愿和你化做一团火焰

啊啊啊

千年等一回

等一回啊

千年等一回

我无悔啊

千年等一回

等一回啊

千年等一回

我无悔啊

千年等一回

## 东北摇篮曲 {- #lullaby}
[点击收听](https://y.qq.com/n/ryqq/songDetail/003MDpDy2Bzy69)

***
周深

***

月儿明风儿静

树叶儿遮窗棂啊

蛐蛐儿叫铮铮

好比那琴弦声啊

琴声儿轻 调儿动听

摇篮轻摆动啊

亲爱的宝宝 闭上眼睛

睡了那个睡在梦中

报时钟响叮咚

夜深人儿静啊

小宝宝 快长大

为祖国立大功啊

月儿那个明

风儿那个静

摇篮轻摆动啊

亲爱的宝宝 睡在梦中

微微地露了笑容

月儿明风儿静

树叶儿遮窗棂啊

蛐蛐儿叫铮铮

好比那琴弦声啊

琴声儿轻 调儿动听

摇篮轻摆动啊

亲爱的宝宝 闭上眼睛

睡了那个睡在梦中

啦啦啦啦啦

啦啦啦啦啦

啦啦啦啦啦啦啦

啦啦啦啦啦啦啦啦

## 奇迹时刻 {- #magic-moment}
[点击收听](https://y.qq.com/n/ryqq/songDetail/002hBt7V3cwn1y)

***
周深

词：吕易秋 (SBMS)

曲：Kai Takahashi(LUCKY TAPES)/胡臻koshin

编曲：Kai Takahashi(LUCKY TAPES)/胡臻koshin

制作人：Kai Takahashi(LUCKY TAPES)

***

从银河 抹去的恒星 穿梭时空的王牌

一个瞬息就能将 不思议解开 (get up)

礼帽 会翻出精灵 还是一整片星海

那悬念 在左手或右手 never know (never know)

这世界总有太多 陆离光怪

以惊喜回应期待 we can dream we can fly

若相信 谁都可以 重塑现在

不需要等待show time 此刻就无限精彩

I wanna see my way in the starlight

奇迹时刻 等你一起来

开启夺目现在

We gonna change the fate never deny

以无数颗 渺小的光彩

就能照亮 无穷未来

别眨眼 错过这幕精彩

We can follow our inside

只要 我们彼此信赖

就能将命运更改

无所谓 一切多 千奇百怪

以最单纯 魔力和热爱

就能一起 冲破阻碍

别关注 错综的光影 现实永远有意外

一根丝线就能牵 动星球离开 (Patient)

如果 要找回自己 线索在九霄云外

无论要 去多远的宇宙 here we go (here we go)

这世界总有太多 陆离光怪

以惊喜回应期待 we can dream we can fly

若相信 谁都可以 重塑现在

不需要等待show time 此刻就无限精彩

I wanna see my way in the starlight

奇迹时刻 等你一起来

开启夺目现在

We gonna change the fate never deny

以无数颗 渺小的光彩

就能照亮 无穷未来

Yea

Set me free 怎么移星换影 只可意会

Don't be afraid 打出一个响指 揭示原委

Let's play 变几束玫瑰 让他们赞美

当视线交汇 才是最完美的机会

Just transform trick in a quick pause

选择中庸的把戏 才最无聊

魔术绝非无中生有 变数早有预兆

这道理简单 自作聪明更可笑

Yea ready for this

Enjoy the show

I wanna see my way in the starlight

奇迹时刻 等你一起来

开启夺目现在

We gonna change the fate never deny

以无数颗 渺小的光彩

就能照亮 无穷未来

让我们 成就夺目精彩

We can light up our true life

就让 奇迹与我同在

将这命运都更改

就算这 一切总 千奇百怪

以最单纯 魔力和热爱

就能一起 冲破阻碍

让我们 成就夺目精彩

We can light up our true life

就让 奇迹与我同在

将这命运都更改

就算这 一切总 千奇百怪

以最单纯 魔力和热爱

就能一起 冲破阻碍

## 生日祝福歌 {- #happy-birthday}
[点击收听](https://y.qq.com/n/ryqq/songDetail/001Mk9Yx0Rkkvp)

***
周深

***

祝你生日快乐

今天你生日

送上我祝福

特别的日子有灿烂的笑容

我们来相聚

带着满满的关爱

祝福你好运常伴

点燃了蜡烛

许下你心愿

未来的日子每个梦想都实现

唱首祝福歌

我们相亲又相爱

祝福你健康平安

对所有的烦恼说 bye bye

对所有的快乐说 hi hi

亲爱的亲爱的生日快乐

每一天都精彩

看幸福的花儿为你盛开

听美妙的音乐为你喝彩

亲爱的亲爱的生日快乐

祝你幸福永远

幸福永远

点燃了蜡烛

许下你心愿

未来的日子每个梦想都实现

唱首祝福歌

我们相亲又相爱

祝福你健康平安

对所有的烦恼说 bye bye

对所有的快乐说 hi hi

亲爱的亲爱的生日快乐

每一天都精彩

看幸福的花儿为你盛开

听美妙的音乐为你喝彩

亲爱的亲爱的生日快乐

祝你幸福永远

幸福永远

生日快乐

生日快乐

生日快乐

对所有的烦恼说 bye bye

对所有的快乐说 hi hi

亲爱的亲爱的生日快乐

每一天都精彩

看幸福的花儿为你盛开

听美妙的音乐为你喝彩

亲爱的亲爱的生日快乐

祝你幸福永远

幸福永远

## wala li longla {- #wala-li-longla}
[点击收听](https://y.qq.com/n/ryqq/songDetail/0015sIpZ4CYA8X)

***
周深

词：李聪

曲：Isabelle Molin/Gustaf Holter/Christian Persson

编曲：Isabelle Molin/Gustaf Holter/Christian Persson

制作人：钱雷

***

把蜗牛都放大 把汽泡堆成塔

口味自由混搭 用沙砾提炼火花

无所谓章法 无所谓多伟大

一默念就触发 ha

Wala li longla

Ah

从月球一瞬移 转场罗马

Xili yo huala

Ah

心愿会解码成 烟花挥洒

变爱德华 或玛格丽塔

甜美或辛辣

快乐没时差

Ah

Wala li longla

繁星里去涂鸦 找鲸鱼喝杯茶

跨服务器抵达 美梦可以一键带回家

无所谓复杂 遨游到更浮夸

一默念就触发 drr

Wala li longla

Ah

从月球一瞬移 转场罗马

Xili yo huala

Ah

心愿会解码成 烟花挥洒

变爱德华 或玛格丽塔

甜美或辛辣

快乐没时差

Ah

Wala li longda

我读取浪花 不只是浪花

面包和陨石 同等无价

快乐没时差

Wala li longla

我看的永恒 都是一刹那

虚拟与现实 无缝融洽

Wala li longla

快乐最伟大

Wala li longla

Ah

白垩纪跳到 西游记玩耍

Xili yo huala

Ah

全世界 随心意 解锁密码

管它奇葩 还是没想法

乖张或优雅

Wala li longla

Ah

Xili yo huala

Wala li longla

Ah

白垩纪跳到 西游记玩耍

Xili yo huala

Ah

全世界 随心意 解锁密码

管它奇葩 还是没想法

乖张或优雅

Wala li longla

Ah

Xili yo huala




## 太阳出来喜洋洋 {- #happy-sun}
[点击收听](https://y.qq.com/n/ryqq/songDetail/004Td9tO4H0LVa)

***
词：金鼓

曲：蓝河

***

太阳出来 啰儿

喜洋洋啰 啷啰

挑起扁担 啷啷啋 咣啋

上山岗啰 啷啰

手里拿把 啰儿

开山斧啰 啷啰

不怕虎豹 啷啷啋 咣啋

和豺狼啰 啷啰

悬崖陡坎 啰儿

不稀罕啰 啷啰

唱起歌儿 啷啷啋 咣啋

忙砍柴啰 啰啰

走了一山 啰儿

又一山啰 啷啰

这山去了 啷啷啋 咣啋

那山来啰 啰啰

只要我们 啰儿

多勤快啰 啷啰

不愁吃来 啷啷啋 咣啋

不愁穿啰 啰啰

## 山城棒棒军 {- #nice-chongqing}
[点击收听](https://y.qq.com/n/ryqq/songDetail/004RDSuA4Bq460)

***
周深

***

开门季节是咿呀伊尔哟

柴米油盐酱呀酱醋茶

咿呀伊尔哟 酱呀酱醋茶

人生五种味 酸甜苦麻辣

人生五种味 酸甜苦麻辣

解放碑 来来往往

大码头上上下下

咿呀伊尔哟 上上下下

七十二行新添一行

七十二呀行 新添一行

嘿咻 嘿咻

嘿咻 哟吼

大街小巷 有我一根棒棒

南竹当自立 男儿当自强

咿呀伊尔哟 男儿当自强

日子悠悠过 山高水长

开口张小哥 天宽地广

咿呀伊尔哟 天宽地广

嘿嘿 嘿嘿

重庆 雄起

重庆 雄起

重庆 雄起

重庆 雄起

重庆 雄起

重庆 雄起

重庆 雄起

你们都是最棒的

南竹当自立 男儿当自强

咿呀伊尔哟 男儿当自强

日子悠悠过 山高水长

开口张小哥 天宽地广

咿呀伊尔哟 天宽地广

天宽地广

## 璀璨冒险人 {- #adventurers}
[点击收听](https://y.qq.com/n/ryqq/songDetail/000zmMlz1J0bsy)

***
周深

词：郑志焕/曹德智/陈小信

曲：钱雷

编曲：钱雷

制作人：钱雷

***

这个世界 是什么模样

走过山水一程 梦一场

那迎风呐喊的海浪

要多久 多久才会遇上

冒险的人 是否会感伤

终其璀璨一生 谁收藏

那深埋心底的愿望

要多久 多久才会登场

沿途一身泥泞 跌撞的是我

忍痛缓行不回头的 也是我

就让一路曲折 每一道伤口

洗净我的脆弱

原来 咽回去的泪

才能 淹没了脆弱

你 发誓更勇敢 一生与梦相拥

还 想要继续吗

要 逆风不退啊

让璀璨住进 你眼眸

别怕 未来的模样

辜负 曾经的凝望

有 多少理想 就有 多少次传唱

那 沿途的风浪

也 不过就这样

这一路光景 有你在身旁

Rap：

他们说要越过 前方风沙 必须低着头

他们说要绕过 蜿蜒的河 才能往前走

他们说烫要放手 太远要换个路口

如果得不到谁的认同 那就不算拥有

没人能够决定 谁的一生 应该怎么活

没人能够定义 谁的天空 是什么颜色

没人未梦就先懂 只是单纯相信着

背向光的英雄 每张轮廓

出自平凡的沉默

沿途一身泥泞 跌撞的是我

忍痛缓行不回头的 也是我

就让一路曲折 每一道伤口

洗净我的脆弱

原来 咽回去的泪

才能 淹没了脆弱

你 发誓更勇敢 一生与梦相拥

还 想要继续吗

要 逆风不退啊

让痛苦住进 你眼眸

别怕 未来的模样

辜负 曾经的凝望

有 多少理想 就有 多少次传唱

那 沿途的风浪

也 不过就这样

这一路光景 有你在身旁

要炙热啊 要不忘啊 要勇往啊

起风了 呼唤了 你还在等什么

挥手了 再见了 别不舍回头啊

向心中的梦啊 去追吧

要能留下伤痕才算活过

愿你记得

愿你哭过 不惧脆弱

## 来不及勇敢 {- #late-to-be-brave}
[点击收听](https://y.qq.com/n/ryqq/songDetail/000LX4oT0zWsIt)

***
周深

词：樊帆/金灿灿

曲：钱雷

编曲：钱雷

***

自行车向前转动着时光

在后座遗落了谁目光

不曾想你穿着校服模样

也从我生活离场

风吹过吹旧了那条小巷

到尽头追不到你余光

我的梦只有你懂得欣赏

那是最美的时光

都是我还来不及学会勇敢

让你一个人孤单

我害怕青春就此离散

让遗憾成遗憾

你我从此无关

遗憾是片青春的书签

夹在了最痛的那一页

那个夏天像秋天的落叶

假装灿烂不害怕离别

一场大雨湿透整个世界

流逝我们的一切

都是我还来不及学会勇敢

让你一个人走散

我多想能像昨天一样

任凭青春荒唐

你不要再悲伤

都是我还来不及学会勇敢

恨这一生太短暂

我愿意用所有去交换

换为时还不晚

换余生不孤单

啦啦啦 啦啦啦啦啦啦

啦啦啦 啦啦啦啦啦啦

## 夏日友晴天 {- #sunny-day-in-summer}
[点击收听](https://y.qq.com/n/ryqq/songDetail/004F84Ml0bYWrJ)

***
周深

词：王雪野

曲：王登辉

编曲：王东宇/林逸航

制作人：王东宇

***

阳光柠檬味的盛夏

跳进冰镇的浪花

云朵在天空里涂鸦

海风吹来了晴朗

与 你不期遇见

夏日友晴天

美好都呈现

多幸运

在这个夏季

欢笑奇遇 有你一起

翻越海底 就是天晴

陪伴你

去探索陆地

未解开的谜也会赋予我们勇气

这世界会有你我姓名

慵懒踩着温暖细沙

小摩托追着晚霞

月光船儿倒映成画

星空洒下了童话

与 你不期遇见

夏日友晴天

美好都呈现

多幸运

在这个夏季

欢笑奇遇 有你一起

翻越海底 就是天晴

陪伴你

去探索陆地

未解开的谜也会赋予我们勇气

这世界会有你我姓名

哼唱：

多幸运

在这个夏季

欢笑奇遇 有你一起

翻越海底 就是天晴

陪伴你

去探索陆地

未解开的谜总会给我们勇气

这世界会有你我姓名

## 可它爱着这个世界 {- #love-the-world}
[点击收听](https://y.qq.com/n/ryqq/songDetail/0002zbK23I9Ck1)

***
周深

词：沃特艾文儿

曲：周深

编曲：茶茶

制作人：徐威/周深

***

无风的街角扬起了几缕尘埃

柳枝也打了几个太轻柔的摆

你未曾留意

亦未曾知它们存在

那些都是面容丑陋的妖怪

温柔珍藏眸中人情百态

太孤独缄默

却比人们更懂得爱

它也曾伫立街头任车马穿身过

携满肩风雪满腔寂寞

却仍愿 坚信着

世间最美好的一切

正御风漂泊

它仍对你第一万次展颜微笑了

小心翼翼也略显笨拙

而你从未得知那种渺小的温热

多么动人心魄

追着风 逐向云 奔向尘世

怀揣着 千百年 的爱与执

这相遇 那离别

都成就值得珍藏的故事

它正虔诚静候着

与你擦肩时

你轻声 蓦然念出它陈旧却

珍贵的名字

它也曾不发一言连年孤身流浪

去拥抱那束暖金的光

拾起的 这回忆

无论喜或悲伤都

随光阴绵长

它还是默默地长久地深情地观望

时光中的人来与人往

那幅无声的画面太过稀疏寻常

竟也触目惊心

你也曾不经意隔空予它一笑容

轻而飘渺却珍而又重

霞光中 乘着风

化作它荒寂心头上

最柔软的梦

你听着友人帐中生命不息的脉动

看落尘故事逐一解封

某种似曾相识难以言表的感动

让你润湿眼瞳

某种似曾相识难以言表的感动

让你润湿眼瞳

## 时结 {- #shijie}
[点击收听](https://y.qq.com/n/ryqq/songDetail/003w9ogC3Zez2l)

***
周深

词：青道/捷喜米(刘捷)/冥凰/白领悟

曲：黎子明/朱天尧/刘润洁

编曲：陈稷坤/Bingo/裴彦淳

制作人：周深/陈稷坤

***

少年的脚步 跌撞

踏一片春色 留芳

追随纸鸢的线 去回望

划破了过往

载上希望 翱翔

听 锣鼓声声

引千帆破浪

岁月悠悠

留一抹浅香

探讨几人

年月描摹的模样

与 时光对抗

尽是少年郎

天高水阔

越是想象 越是向往

去远方

结下花草香

结下碧波荡漾

再结下 你我牵绊

蓦然回首

仍是最初模样

结下明月光

结下念想

结下岁月

又一场

绣一片星光 流淌

搭一座桥梁 相望

手中缠绕的结 在绽放

把繁星点亮

添花锦上 传唱

看 人聚人散

赏月忆过往

那只玉兔

捣药桂树旁

月圆飘香

欢饮达旦 又何妨

待 天涯此时

可谈尽衷肠

人海茫茫

借着月光 相逢一方

不相忘

结下花草香

结下碧波荡漾

再结下 你我牵绊

蓦然回首

仍是最初模样

结下明月光

结下念想

结下岁月

又一场

当这一绳一结 为你缠绕我的思念

这编织的挂念 抵挡住时间的变迁

别让眷念 沦落成夙愿

消失在指尖

结下花草香

结下碧波荡漾

再结下 你我牵绊

蓦然回首

仍是最初模样

结下明月光

结下念想

结下流年

不散场

结下流年

不散场

## 请笃信一个梦 {- #believe-your-dream}
[点击收听](https://y.qq.com/n/ryqq/songDetail/0044RGRO1KPVq0)

***
周深

词：沃特艾文儿

曲：陈禹

编曲：陈禹/李建衡/向心·引力studio

***

我们在途中匆匆挥手并不说告别

只因深知总会在轮回里再次相见

到那天穿过陌生人海在闹市中擦肩

平凡的梦啊终会被成全

幸好你从未因疲惫选择停留

有熟稔的呼唤声引你向前走

正是懵懂的眼眸才将世事看通透

内心始终笃信爱与温柔

但愿这漫天时起时落的星斗

曾照拂过的人们都能被庇佑

在颠沛之中漂流于不经意的时候

你会与你的梦悄然邂逅

你一路迎向那被黄昏染红的天边

怀揣着来世的梦走向今生的终结

就这样渐行渐远直到再也看不真切

未尽的执念都留在这人间

无需一再去追问从前或以后

能在时空中相逢就已然足够

不顾一切去握紧那双向你伸的手

一刻安谧便是天长地久

你一路迎向那被黄昏染红的天边

怀揣着来世的梦走向今生的终结

最后微笑着回身遥遥朝那人望一眼

终于开始学会眷恋这人间

我们在途中匆匆挥手并不说告别

只因深知总会在轮回里再次相见

最后微笑着回身遥遥朝那人望一眼

终于开始学会眷恋这人间

终于开始学会眷恋这人间

终于开始学会眷恋这人间

## 微光海洋 {- #sea-of-shimmer}
[点击收听](https://y.qq.com/n/ryqq/songDetail/003FxomC2BTqEV)

***
周深

词：RIO(Ryota Kawamura)/Haruka Sakai/谢乔翰

曲：RIO(Ryota Kawamura)/Haruka Sakai

编曲：RIO(Ryota Kawamura）/何官錠AL

***

向 日出的方向 远远地眺望

告别了海港 扬起了帆

我就要启航

面向朝阳 淡淡的金黄 将你晕染

如诗画的模样

用心听 潮汐的呼唤

穿越了 狂风和骇浪

迷航的旅途 太漫长

你站在礁岸

手中那盏飘渺微光

暗夜的希望

想化作天空 化作海洋

带你去任何地方

守护着你 不管世界 变成什么样

想化作飞鸟 化作骄阳

为你指引着方向

爱的牵绊 成为照亮 彼此的光

啦 啦 啦 守护着

啦 啦 啦 不用害怕

啦 啦 啦 守护着

啦 啦 啦 无畏吧

在 无际的海上 迷雾中游荡

而你用温柔 抚平迷惘

皎洁的月光

洒落甲板 纤弱的肩膀 独自承担

太多隐忍不甘

用心听 潮汐的呼唤

穿过了 惊涛和骇浪

迷航的旅途 太漫长

你站在礁岸

手中那盏飘渺微光

暗夜的希望

想化作天空 化作海洋

带你去任何地方

守护着你 不管世界 变成什么样

想化作飞鸟 化作骄阳

为你指引着方向

爱的牵绊 成为照亮 彼此的光

清澈眼神 透出 那份倔强

传递给我 无尽 的力量

乘风浪 飞跃过阻碍

在一起 和命运对抗

手中温暖 驱散 夜的极寒

你在身旁 让我 不再迷茫

逆风 扶摇 而上

勇敢 向前方

想化作天空 化作海洋

带你去任何地方

守护着你 不管世界 变成什么样

想化作飞鸟 化作骄阳

为你指引着方向

爱的牵绊 冲破了黑暗

想化作天空 化作海洋

带你去任何地方

守护着你 不管世界 变成什么样

想化作飞鸟 化作骄阳

为你指引着方向

爱的牵绊 成为照亮 彼此的光

啦 啦 啦 守护着

啦 啦 啦 不用害怕

啦 啦 啦 守护着

啦 啦 啦 无畏吧

## 三餐四季 {- #three-meals-a-day}
[点击收听](https://y.qq.com/n/ryqq/songDetail/003atI222IgbwG)

***
周深

词：周萌/吴崎伟/赵楚峰

曲：刘逸君

制作人：赵楚峰BackToBand

***

楼上姑姑家 总炖着桂花

香味慢慢融化

转眼三年了 灯再也没亮着

儿子也没回家

院子梧桐下 围着旧篱笆

无论风吹雨打

到日落黄昏 放学会经过它

月挂上了枝桠

叔父喜欢喝茶 女儿很听话

每天帮着浇花

她只想在家 叔父白了发

叹时光如流沙

想去追梦啊 音符画成画

妈妈放心不下

可她不甘心 独自在晚霞

总盼望真正地长大

生命几克梦千两

承载了万分渴望

记忆绵长泛微光

三餐四季慢慢荡

行囊不重重思量

山前旷阔轻踏上

你在来时的路旁

轻轻对我说一句

别来无恙

爸爸工作太忙 总很晚回家

夜色承接朝霞

春秋到冬夏 没一刻闲暇

如今我也像他

年复一年啊 爱没有落差

妈妈从未停下

这一碗热汤 和唠叨的话

不知不觉我已长大

生命几克梦千两

承载了万分渴望

记忆绵长泛微光

三餐四季慢慢荡

行囊不重重思量

山前旷阔轻踏上

你在来时的路旁

轻轻对我说一句

别来无恙

## 海藏 {- #ocean-treasure}
[点击收听](https://y.qq.com/n/ryqq/songDetail/001ga9Cr36eWar)

***
周深

词：刘恩汛

曲：苟音

***

你若是 星辰夜色

流落海上泪珠一颗

陪伴我 颠沛成渔火

多闪烁

等风来 倾听经过

扬帆你我命运起落

前方路 用泥泞勾勒

也都值得

我 徘徊过 无助过 倔强过

心像漂泊的孤舟 你是追随的浪朵

梦 辗转过 期盼过 痛醒过

如果流浪 再坎坷 不闪躲

时光的变迁 四海潮升凝望间

逆水如流年 情愫又怎能如烟

当故里渐远 多庆幸有你在身边

初心不凋谢 四海潮升着眷恋

若爱是深渊 纵身漩涡也成全

他日重逢我仍是 无畏少年

月光下 我的轮廓

寻遍海藏秘岛斑驳

萦绕着 你悠扬余歌

多清澈

看着你 为我回眸

云散天开温柔辽阔

去暖透 离愁的落寞

彼此诉说

我 徘徊过 无助过 倔强过

心像漂泊的孤舟 你是追随的浪朵

梦 辗转过 期盼过 痛醒过

如果流浪 再坎坷 不闪躲

时光的变迁 四海潮升凝望间

逆水如流年 情愫又怎能如烟

当故里渐远 多庆幸有你在身边

初心不凋谢 四海潮升着眷恋

若爱是深渊 纵身漩涡也成全

他日重逢我仍是 无畏少年

## 跳舞的月光 {- #dancing-moonshine}
[点击收听](https://y.qq.com/n/ryqq/songDetail/0008Qdba0T7qvu)

***
周深

词：唐恬

曲：李吉吉

编曲：李吉吉

***

你能 听见 我吗

未曾 抵达 的话

寄给月光 会收到吗

想念 一个 人像

我和影子 跳起舞啊

沉默而喧哗

好想 在黑暗中 奔向你

以我的心跳呼唤你

在人群背影认出你

摇摇晃晃朝你飞行 飞行

Wu

每当我们 各自仰望着月亮

Wu

目光就会 相遇在天上

Wu

分开之后 一定也会想念吧

风的呼唤 哦月的细语

一路陪我追光 不再孤单

好想啊 在黑暗中 奔向你

以我的心跳呼唤你

在人群背影认出你

摇摇晃晃朝你飞行 朝你飞行

Wu

每当我们 各自仰望着月亮

Wu

目光就会 相遇在天上

Wu

分开之后 一定也会想念吧

风的呼唤 哦月的细语

一路陪我追光 不再孤单

Wu 你能听见我吗

每当我们 各自仰望着月亮

Wu 不要害怕

目光就会 相遇在

Wu 你也在等我吗

分开之后 一定也会想念吧

夜路很长 去不同方向

总有一抹月光在心上

## 随风 {- #with-wind}
[点击收听](https://y.qq.com/n/ryqq/songDetail/003zjYy20KTJG4)

***
周深

词：余庆/Léa (任雅静)

曲：Léa (任雅静)/Bryan (孙伟)

编曲：Terence Teo

制作人：王福/Léa (任雅静)

***

更暗 夜更暗 回头空街一段

弥漫 风弥漫 四季推波助澜

大雨将悲欢都冲淡

往事在风中肆无忌惮

看似过去 却从未走远

拥抱的温存 梦醒一半

哦 道别声还在耳畔

哦 诉说声不忍再看

哦 命运声风轻云淡

哦 让是非与你无关

我的慌乱 我的伪装

我的不舍 被你一眼看穿

情剪不断 也不愿剪断

再见难说 故事还没完

道别 又道别 汽笛声在呼唤

想念 还想念 往事被泪晕染

月光将迷雾都驱散

回忆似梦境又似迷幻

看似过去 却还在纠缠

拥抱的温存 随风而散

道别声还在耳畔

哦 诉说声不忍再看

哦 命运声风轻云淡

哦 让是非与你无关

我的慌乱 我的伪装

我的不舍 被你一眼看穿

情剪不断 也不愿剪断

再见难说 故事还没完

哦

啊

哦 让是非与你无关

我的慌乱 我的伪装

我的不舍 被你一眼看穿

情剪不断 也不愿剪断

再见难说 故事还没完


## 一缕执念 {- #a-wisp-of-obsession}
[点击收听](https://y.qq.com/n/ryqq/songDetail/0046dc7c2H0SQB)

***
周深

词：高晓松/尹约

曲：钱雷

编曲：张筱真/钱雷

制作人：尹约

***

海尽头的人烟

漫过了远山

漫过了心田的里边

你住在人海边

一袭旧衣衫

一柄油纸伞的对面

昨日鲜衣怒马陌上白衣少年

今天眉宇苍苍看不清你的脸

梦中再照面已不会地转天旋

醒来一肩夕阳零落的碎片

你是我的一缕执念

缠住我的发 藕断丝连

我以为自己 已成熟好几遍

我以为自己 已开始冬眠

你是我的一缕执念

跋山涉水也 跟着我蔓延

我已为了你 参透了枯木禅

我已为了你 去看了远山

你是我的一缕执念

缠住我的发 藕断丝连

我以为自己 已成熟好几遍

我以为自己 已开始冬眠

你是我的一缕执念

跋山涉水也 跟着我蔓延

我已为了你 参透了枯木禅

我已为了你 去看了远山

## 拙慕 {- #inferior-admiration}
[点击收听](https://y.qq.com/n/ryqq/songDetail/0042QR5D2I7k9T)

***
周深

词：江岸

曲：和汇慧/王梓同

编曲：赵越

制作人：和汇慧

***

要如何称呼

才把故事引出

好让我 启齿不唐突 有心含糊

若向你汲足

被风与雪放逐

好过 朝暮苦想着 乱意成荒芜

坠入迷雾

掩埋下悲哭

饮冰代热血

无畏一场拙慕

相熟也生疏

咫尺一步

是我徒劳拙慕

世间多沉浮

不是义无反顾

狂奔着 都能到尽处 慰情胜无

所以会盲目

也会觉得辛苦

只是你 一回身我会放下全部

坠入迷雾

掩埋下悲哭

饮冰代热血

无畏一场拙慕

相熟也生疏

咫尺一步

是我徒劳拙慕

坠入迷雾

掩埋下悲哭

饮冰代热血

无畏一场拙慕

相熟也生疏

咫尺一步

是我徒劳拙慕

敬我无畏拙慕

## 贝加尔湖畔 {- #lake-baikal}
[点击收听](https://y.qq.com/n/ryqq/songDetail/003wEVyt00ClRb)

***
周深

词：李健

曲：李健

编曲：谭伊哲

***

在我的怀里

在你的眼里

那里春风沉醉

那里绿草如茵

月光把爱恋

洒满了湖面

两个人的篝火

照亮整个夜晚

多少年以后

如云般游走

那变换的脚步

让我们难牵手

这一生一世

有多少你我

被吞没在月光如水的夜里

多想某一天

往日又重现

我们流连忘返

在贝加尔湖畔

多少年以后

往事随云走

那纷飞的冰雪容不下那温柔

这一生一世

这时间太少

不够证明融化冰雪的深情

就在某一天

你忽然出现

你清澈又神秘

在贝加尔湖畔

你清澈又神秘

像贝加尔湖畔

## 春雪 {- #spring-snow}
[点击收听](https://y.qq.com/n/ryqq/songDetail/0034Ykph3iVfpt)

***
周深

作词：Terry Zhong 钟天利/王子zione

作曲：Terry Zhong 钟天利/王子zione

编曲/制作：Terry Zhong 钟天利

***

白是无尽的迷途

白是归零的法术

洗净 染渍 反复

练就成我温暖天赋 也不免再惹一身寒毒

冰是雪送的礼物

却不敌春来时的温度

融化 难以 碰触

沿着心底返流灌注 到面孔化作几滴泪珠

我想在冬夜雪地与你追逐

你却落在早春中的一棵树

一次错过不算错误

错在来不及看清楚

你的面目我就交出全部

雪花开在冬夜深处蔓延

蔓延到一个危险的春天

春天蚕食消融目空一切

一切啊那曾是我的世界

雪花开在冬夜深处蔓延

蔓延到一个危险的春天

我在原地守护我的体面

春天再见 春天再见

我还在冬夜雪地里等日出

你落满早春枝叶宣判我输

趁这错过还没结束

再请你跳一支舞

画下曼妙脚步作为庆祝

趁这错过还没结束

再送你一句祝福

落下枝叶时有人来接住

## 孤独的牧羊人 {- #lonely-shepherd}
[点击收听](https://y.qq.com/n/ryqq/songDetail/002NWrLt2Ghyix)

***
周深

词：Oscar Hammerstein II/Richard Rodgers

曲：Oscar Hammerstein II/Richard Rodgers
***

High on a hill was a lonely goatherd

Lay ee odl lay ee odl lay hee hoo

Loud was the voice of the lonely goatherd

Lay ee odl lay ee odl oo

Folks in a town that was quite remote heard

Lay ee odl lay ee odl lay hee hoo

Lusty and clear from the goatherd's throat heard

Lay ee odl lay ee odl oo

O ho lay dee odl lee o

O ho lay dee odl oo

O ho lay dee odl lee o

Lay dee odl lee oo

A prince on the bridge of a castle moat heard

Lay ee odl lay ee odl lay ah ah

Men on a road with a load to tote heard

Lay ee odl lay ee odl oh

Men in the midst of a table d'hote heard

Lay ee odl lay ee odl lay hee hoo

Men drinking beer with the foam afloat heard

Lay ee odl lay ee odl

One little girl in a pale pink coat heard

Lay ee odl lay ee odl lay hee hoo

She yodeled back to the lonely goatherd

Lay ee odl lay ee odl oo

Soon her Mama with a gleaming gloat heard

Lay ee odl lay ee odl lay hee hoo

O lay ee o lay ee odl

Lay ee odl lay ee odl oo

O Happy are they odl o lay dee lee o

O lay dee o lay dee lay ee o

Soon the duet will become a trio

Lay ee odl lay ee odl oo

Odl lay ee

Odl lay ee

Odl lay hee hee

Odl lay ee

Odl lay odl lay

Odl lay odl lay

Odl lay odl lay

Odl lay odl lay odl lay

## 漂洋过海来看你 {- #across-the-ocean-to-see-you}
[点击收听](https://y.qq.com/n/ryqq/songDetail/003P20Zd3RYfoI)

***
周深

词：李宗盛

曲：李宗盛
***

为你我用了半年的积蓄

飘洋过海的来看你

为了这次相聚

我连见面时的呼吸都曾反复练习

言语从来没能将我的情意

表达千万分之一

为了这个遗憾

我在夜里想了又想不肯睡去

记忆它总是慢慢的累积

在我心中无法抹去

为了你的承诺

我在最绝望的时候

都忍着不哭泣

陌生的城市啊

熟悉的角落里

也曾彼此安慰 也曾相拥叹息

不管将会面对什么样的结局

在漫天风沙里望着你远去

我竟悲伤的不能自已

多盼能送君千里

直到山穷水尽

一生和你相依

陌生的城市啊

熟悉的角落里

也曾彼此安慰 也曾相拥叹息

不管将会面对什么样的结局

在漫天风沙里望着你远去

我竟悲伤的不能自已

多盼能送君千里

直到山穷水尽

一生和你相依

多盼能送君千里

直到山穷水尽

一生和你相依

## 如愿 {- #achieve-wishes}
[点击收听](https://y.qq.com/n/ryqq/songDetail/0016O7hh1h111I)

***
周深

词：唐恬

曲：钱雷
***

你是 遥遥的路

山野大雾里的灯

我是孩童啊 走在你的眼眸

你是 明月清风

我是你照拂的梦

见与不见都一生 与你相拥

而我将 爱你所爱的人间

愿你所愿的笑颜

你的手我蹒跚在牵

请带我去明天

如果说 你曾苦过我的甜

我愿活成你的愿

愿不枉啊 愿勇往啊

这盛世每一天

你是 岁月长河

星火燃起的天空

我是仰望者 就把你唱成歌

你是 我之所来

也是我心之所归

世间所有路都将 与你相逢

而我将 爱你所爱的人间

愿你所愿的笑颜

你的手我蹒跚在牵

请带我去明天

如果说 你曾苦过我的甜

我愿活成你的愿

愿不枉啊 愿勇往啊

这盛世每一天

山河无恙 烟火寻常

可是你如愿的眺望

孩子们啊 安睡梦乡

像你深爱的那样

而我将 梦你所梦的团圆

而我将 梦你所梦的团圆

愿你所愿的永远

走你所走的长路

这样的爱你啊

我也将 见你未见的世界

写你未写的诗篇

天边的月 心中的念

你永在我身边

与你相约 一生清澈

如你年轻的脸

## 和光同尘 {- #stay-with-light}
[点击收听](https://y.qq.com/n/ryqq/songDetail/00081KVW1lL09U)

***
周深

词：董颖达

曲：董颖达

编曲：董颖达

制作人：董颖达

***

和你一起歌

和你一起合

月落星沉

日出东海

和你走过

理想的大河

从容的

沸腾着

你看那 盛放的花儿

来自期盼的种子

你看那 丰硕果实

来自耕耘的浪漫

宽广的大河

来自八方汇聚的小溪

奔腾向前的大江

来自高山的哺育

和光同行

跌跌撞撞的摸索

和光同舞

奋不顾身的坎坷

和光同尘

不为盛名而来

不为低谷而去

你看那 盛放的花儿

来自期盼的种子

你看那 丰硕果实

来自耕耘的浪漫

宽广的大河

来自八方汇聚的小溪

奔腾向前的大江

来自高山的哺育

和光同行

跌跌撞撞的摸索

和光同舞

奋不顾身的坎坷

和光同尘

不为盛名而来

不为低谷而去

你看那 盛放的花儿

来自期盼的种子

你看那 丰硕果实

来自耕耘的浪漫

和光同尘

不为盛名而来

不为低谷而去

和光同行

跌跌撞撞的摸索

和光同舞

奋不顾身的坎坷

和光同尘

不为盛名而来

不为低谷而去

和光同尘

为你而来

有你 我在

## 只字不提 {- #nothing-to-say}
[点击收听](https://y.qq.com/n/ryqq/songDetail/004LJOTh3m2kyK)

***
周深

词：赵楠/包安全

曲：周月/包安全
***

街边 偶遇熟悉陌生的你

擦肩 你头也没回便远去

风吹得肆意

冻结了记忆

却始终没法忘记

房间 时钟声音模糊清晰

消息 对话框没任何回应

你已销声匿迹

对我避之不及

只是我还不甘心

后来的你

关于我 已只字不提

仿佛和你

从未有 热烈的经历

熟练地 将这一切规避

此刻的你

还是否会想起曾经

那些过往

还是否苟活在你回忆

曾触手可及的你 在哪里

在哪里

房间 时钟声音模糊清晰

消息 对话框没任何回应

你已销声匿迹

对我避之不及

只是我还不甘心

后来的你

关于我 已只字不提

仿佛和你

从未有 热烈的经历

熟练地 将这一切规避

此刻的你

还是否 会想起曾经

那些过往

还是否苟活在你回忆

曾触手可及的你

在哪里

后来的你 关于我 已只字不提

仿佛和你 从未有 热烈的经历

熟练地 将这一切规避

此刻的你 还是否 会想起曾经

那些过往 还是否苟活在你回忆

曾触手可及的你 在哪里

在哪里

你在哪里

曾触手可及的你 在哪里


## 不想睡 {- #keep-playing}
[点击收听](https://y.qq.com/n/ryqq/songDetail/003tptKO20zzOC)

***
周深

词：宫泽和史

曲：宫泽和史
***

默默自转的星球

冥冥之中你要现在遇见我

我看过 瞬间燃烧的花火

昙花一现之后悄悄的坠落

宇宙中默默自转的星球

冥冥之中你要现在遇见我

我看过 瞬间燃烧的花火

昙花一现之后悄悄的坠落

我醉过 真夏冰酿的梅酒

醒来以后还有你在陪着我

那种微酸的滋味

有点微醺的感觉

梦作一半比较美

爱我的人还没睡

不想睡 我要陪你一整夜

我要幸福的催眠

天旋地转的晕眩

不想睡 我要陪你一整夜

我要今天的完美

不要明天的幻觉

我看过 瞬间燃烧的花火

昙花一现之后悄悄的坠落

我醉过 真夏冰酿的梅酒

醒来以后还有你在陪着我

那种微酸的滋味

有点微醺的感觉

梦作一半比较美

爱我的人还没睡

不想睡 我要陪你一整夜

我要幸福的催眠

天旋地转的晕眩

不想睡 我要陪你一整夜

我要今天的完美

不要明天的幻觉

雪花盛开在风中

是你紧紧抱着我

泪光在闪动

一闪一道彩虹

不想睡我要陪你一整夜

我要幸福的催眠

天旋地转的晕眩

不想睡我要陪你一整夜

我要今天的完美

不要明天的幻觉

啦啦啦啦啦啦

啦啦啦啦啦啦

啦啦啦啦啦啦

啦啦啦啦啦啦

啦啦啦啦啦啦

啦啦啦啦啦啦

啦啦啦啦啦啦

啦啦啦啦啦啦

啦啦啦啦啦啦

啦啦啦啦啦啦

啦啦啦啦啦啦

啦啦啦啦啦啦

啦啦啦啦啦啦

啦啦啦啦啦啦

啦啦啦啦啦啦

啦啦啦啦啦啦

啦啦啦啦啦啦

## 我以渺小爱你 {- #love-you}
[点击收听](https://y.qq.com/n/ryqq/songDetail/000EpEPF1ISlQO)

***
周深

词：唐恬

曲：周以力

编曲：周以力

制作人：周以力
***

啦啦啦啦啦 啦啦啦

啦啦啦啦啦啦啦

我以渺小爱你同行的旅程

最美丽的风景 从不会关上门

天空 荒原 大海和人生

路上做个孩子 又明亮又单纯

如小鹿一样看 星辰

海风送给岛屿 几亿万年的吻

大雨落山川像心跳声

世界那么大 我 是短短的一瞬

以渺小爱你 能不能

请你和我交换 旅途黄昏

海浪和云层

让一切 发生 相遇 幸存

天上有 日月和星辰

地上没有异乡人

都曾呼吸狂奔 相爱支撑

命才成为生

一路有 热泪与天真

拥抱细碎的伤痕

别害怕 鲸鱼在远方吟唱

灯塔的歌声

我以渺小爱你给我的旅程

三亿岁的石头 和一百岁的城

身上落下的雪刚出生

老爷爷的眼神 大树的年轮

在时光面前皆我们

请你和我交换 旅途的风

前方的可能

让一切 发生 相遇 作证

天上有 日月和星辰

地上没有异乡人

都曾呼吸狂奔 相爱支撑

命才成为生

一路有 热泪与天真

拥抱细碎的伤痕

别害怕 鲸鱼在远方吟唱

灯塔的歌声

我以渺小爱你同行的旅程

啦啦啦啦 啦啦啦

啦啦啦啦 啦啦啦

天上有 日月和星辰

地上没有异乡人

都曾呼吸狂奔 相爱支撑

命才成为生

世上有 温柔的灵魂

像萤火飞舞夜深

哪怕空无一人 山谷有灯

寻着光相认

我以渺小爱你同行的旅程

我以短暂爱你不朽的旅程

## 起风了 {- #the-wind-rises}
[点击收听](https://y.qq.com/n/ryqq/songDetail/002w57E00BGzXn)

***
周深

词：米果

曲：高橋優

***

这一路上走走停停

顺着少年漂流的痕迹

迈出车站的前一刻

竟有些犹豫

不禁笑这近乡情怯

仍无法避免

而长野的天

依旧那么暖

风吹起了从前

从前初识这世间

万般流连

看着天边似在眼前

也甘愿赴汤蹈火去走它一遍

如今走过这世间

万般流连

翻过岁月不同侧脸

措不及防闯入你的笑颜

我曾难自拔于世界之大

也沉溺于其中梦话

不得真假 不做挣扎 不惧笑话

我曾将青春翻涌成她

也曾指尖弹出盛夏

心之所动 且就随缘去吧

逆着光行走 任风吹雨打

短短的路走走停停

也有了几分的距离

不知抚摸的是故事 还是段心情

也许期待的不过是 与时间为敌

再次见到你

微凉晨光里

笑得很甜蜜

从前初识这世间

万般流连

看着天边似在眼前

也甘愿赴汤蹈火去走它一遍

如今走过这世间

万般流连

翻过岁月不同侧脸

措不及防闯入你的笑颜

我曾难自拔于世界之大

也沉溺于其中梦话

不做真假 不做挣扎 不惧笑话

我曾将青春翻涌成她

也曾指尖弹出盛夏

心之所动 且就随缘去吧

晚风吹起你鬓间的白发

抚平回忆留下的疤

你的眼中 明暗交杂 一笑生花

暮色遮住你蹒跚的步伐

走进床头藏起的画

画中的你 低着头说话

我仍感叹于世界之大

也沉醉于儿时情话

不剩真假 不做挣扎 无谓笑话

我终将青春还给了她

连同指尖弹出的盛夏

心之所动 就随风去了

以爱之名 你还愿意吗



## 大鱼 {- #big-fish}
[点击收听](https://y.qq.com/n/ryqq/songDetail/004OQ5Mt0EmEzv)

***
周深

词：尹约

曲：钱雷

***

海浪无声将夜幕深深淹没

漫过天空尽头的角落

大鱼在梦境的缝隙里游过

凝望你沉睡的轮廓

看海天一色 听风起雨落

执子手吹散苍茫茫烟波

大鱼的翅膀 已经太辽阔

我松开时间的绳索

怕你飞远去 怕你离我而去

更怕你永远停留在这里

每一滴泪水 都向你流淌去

倒流进天空的海底

海浪无声将夜幕深深淹没

漫过天空尽头的角落

大鱼在梦境的缝隙里游过

凝望你沉睡的轮廓

看海天一色 听风起雨落

执子手吹散苍茫茫烟波

大鱼的翅膀 已经太辽阔

我松开时间的绳索

看你飞远去 看你离我而去

原来你生来就属于天际

每一滴泪水 都向你流淌去

倒流回最初的相遇

## 少管我 {- #watch-ur-manners}
[点击收听](https://y.qq.com/n/ryqq/songDetail/000Im8GK2IurkU)

***
周深

词：吕易秋/周深

曲：钱雷/周深

编曲：钱雷

制作人：钱雷/周深

***

有什么关系 删掉无聊的理由

把沉重身体 传送到热带气候

脑袋放空 吹吹海风

用一场远行 当做逃离的方舟

做生活困兽 不如去浪漫宇宙

烦恼忧愁 全部都抽空

看霓虹长出柔软 的触角

给单调的人换上 缤纷躯壳

下一步向左向右 看心情都不重要

以下个绿灯亮起 做信号

掠过遍布人生指南 的街道

不再回去城市某间 禁锢灵魂的巢

我想我可以 抓住风中飘散的花

不介意 坠入水星或是泥巴

跟现在 握手拥抱道别出发

别停下

我想我成为 阳光蔷薇飞鸟盛夏

或成为 昆虫砂砾一片雪花

我不在乎 将烦恼都忘掉

嘿 少管我

嘿 少管我

看霓虹长出柔软 的触角

给单调的人换上 缤纷躯壳

下一步向左向右 看心情都不重要

以下个绿灯亮起 做信号

掠过遍布人生指南 的街道

不再回去城市某间 禁锢灵魂的巢

我想我可以 抓住风中飘散的花

不介意 坠入水星或是泥巴

跟现在 握手拥抱道别出发

别停下

我想我成为 阳光蔷薇飞鸟盛夏

或成为 昆虫砂砾一片雪花

我不在乎 将烦恼都忘掉

嘿 少管我

将这段旅途

献给那些不堪重负 做礼物

用这段旅途 来结束今日的束缚

对明天毫无保留

## 重启 {- #restart}
[点击收听](https://y.qq.com/n/ryqq/songDetail/002Xjn9r215ehH)

***
周深

词：尹约

曲：Morgan Nagler/Steven Colyer

编曲：Steven Colyer

制作人：钱雷

***

眼泪忍住 回望忍住 我已提前谢幕

心爱记住 遗憾也记住

独自反复 回到最初

人生巨幅拼图

太多次迷路 太多次失误

I'm ready now I'm ready now I'm ready now

重启进度

睁眼看见年轻父母

竟把我到来当作礼物

从此我会忍住不哭

哪怕再无助 别让他们辛苦

Ready now ready now I'm ready now

上轮人生 伤与被伤 孤独已刻骨

这轮要 小心翼翼弥补

遥远守护 继续追逐 或是体面结束

我终于 不再一无是处

与你重逢啊 仍是初相见 我已很满足

I'm ready now I'm ready now I'm ready now

悄悄付出

重来几次才能清楚

每段岔路与每个事故

每条没有尽头旅途

用满身尘土 换渺小幸福

I'm ready now

I'm ready now I'm ready now I'm ready now

I'm ready now

I'm ready now I'm ready now I'm ready now

I'm ready now

I'm ready now I'm ready now I'm ready now

I'm ready now

I'm ready now I'm ready now I'm ready now


