# 9.29Hz巡回演唱会相关资源 {#related-929hz}
&emsp;&emsp;本附录整理收集与9.29Hz巡演相关的资源，包括由工作室发布的回顾视频、官方发布的现场视频、饭拍现场录音及视频等资源，请访问在线版（<https://929hz.com/related-929hz.html>）点击引用链接直接跳转。

- [周深B站](https://space.bilibili.com/3404595) —— @bili-charlie  
- [周深微博](https://weibo.com/1736988591?tabtype=home) —— @weibo-charlie  
- [周深工作室B站](https://space.bilibili.com/3546694058773380) —— @bili-charlie-studio  
- [周深工作室微博](https://weibo.com/u/7478855230?tabtype=home) —— @weibo-charlie-studio  

## 9.29Hz巡演各场回顾vlog {#review-vlog}

- 1. [2024 周深 9.29Hz巡回演唱会 上海站回顾](http://t.cn/A6HHrNhQ) —— @weibo-charlie-studio  

- 2.1. [2024 周深 9.29Hz巡回演唱会 深圳站回顾-微博视频版](http://t.cn/A6QPfLcu) —— @weibo-charlie-studio  
- 2.2. [2024 周深 9.29Hz巡回演唱会 深圳站回顾-B站视频版](https://www.bilibili.com/video/BV1vn4y1Q7z4/?spm_id_from=333.999.0.0&vd_source=34f987e1e09ccd330650f965070ae947) —— @bili-charlie-studio  

- 3.1. [2024 周深 9.29Hz巡回演唱会 成都站回顾-微博视频版](http://t.cn/A6QXdS5N) —— @weibo-charlie-studio  
- 3.2. [2024 周深 9.29Hz巡回演唱会 成都站回顾-B站视频版](https://www.bilibili.com/video/BV1Wx4y1t7PX/?spm_id_from=333.999.0.0&vd_source=34f987e1e09ccd330650f965070ae947) —— @bili-charlie-studio  

- 4.1. [2024 周深 9.29Hz巡回演唱会 贵阳站回顾-微博视频版](http://t.cn/A68VAWdM) —— @weibo-charlie-studio  
- 4.2. [2024 周深 9.29Hz巡回演唱会 贵阳站回顾-B站视频版](https://www.bilibili.com/video/BV1ci421a7aX/?spm_id_from=333.999.0.0&vd_source=34f987e1e09ccd330650f965070ae947) —— @bili-charlie-studio  

- 5.1. [2024 周深 9.29Hz巡回演唱会 武汉站回顾-微博视频版](http://t.cn/A68EeE9A) —— @weibo-charlie-studio  
- 5.2. [2024 周深 9.29Hz巡回演唱会 武汉站回顾-B站视频版](https://www.bilibili.com/video/BV1n4421S7Ye/?spm_id_from=333.999.0.0&vd_source=34f987e1e09ccd330650f965070ae947) —— @bili-charlie-studio  

- 6.1. [2024 周深 9.29Hz巡回演唱会 南京站回顾-微博视频版](http://t.cn/A6RySi6O) —— @weibo-charlie-studio  
- 6.2. [2024 周深 9.29Hz巡回演唱会 南京站回顾-B站视频版](https://www.bilibili.com/video/BV1x2421Z71G/?spm_id_from=333.999.0.0&vd_source=34f987e1e09ccd330650f965070ae947) —— @bili-charlie-studio  

- 7.1. [2024 周深 9.29Hz巡回演唱会 杭州站回顾-微博视频版](http://t.cn/A6RlpCFN) —— @weibo-charlie-studio  
- 7.2. [2024 周深 9.29Hz巡回演唱会 杭州站回顾-B站视频版](https://www.bilibili.com/video/BV1Fypue5Ekf/?spm_id_from=333.999.0.0&vd_source=34f987e1e09ccd330650f965070ae947) —— @bili-charlie-studio  

- 8.1. [2024 周深 9.29Hz巡回演唱会 沈阳站回顾-微博视频版](http://t.cn/A6E7UlnX) —— @weibo-charlie-studio  
- 8.2. [2024 周深 9.29Hz巡回演唱会 沈阳站回顾-B站视频版](https://www.bilibili.com/video/BV1MStEe8ELs/?spm_id_from=333.999.0.0&vd_source=34f987e1e09ccd330650f965070ae947) —— @bili-charlie-studio  

- 9.1. [2024 周深 9.29Hz巡回演唱会 北京站回顾-微博视频版](http://t.cn/A6EoUS7a) —— @weibo-charlie-studio  
- 9.2. [2024 周深 9.29Hz巡回演唱会 北京站回顾-B站视频版](https://www.bilibili.com/video/BV1XrxSeEEbA/?spm_id_from=333.999.0.0&vd_source=34f987e1e09ccd330650f965070ae947) —— @bili-charlie-studio  


```{asis, echo=!knitr::is_latex_output()}
::: {.infobox .student-mi}

**温馨提示：**周深工作室微博发布的回顾视频和B站发的回顾视频内容不完全一样哦~
:::

```
